


<option value="19031">Mackey International Inc.: MAC</option>
<option value="19032">Munz Northern Airlines Inc.: XY</option>
<option value="19033">Cochise Airlines Inc.: COC</option>
<option value="19034">Golden Gate Airlines Inc.: GSA</option>
<option value="19035">Aeromech Inc.: RZZ</option>
<option value="19036">Golden West Airlines Co.: GLW</option>
<option value="19037">Puerto Rico Intl Airlines: PRN</option>
<option value="19038">Air America Inc.: STZ</option>
<option value="19039">Swift Aire Lines Inc.: SWT</option>
<option value="19040">American Central Airlines: TSF</option>
<option value="19041">Valdez Airlines: VEZ</option>
<option value="19042">Southeast Alaska Airlines: WEB</option>
<option value="19043">Altair Airlines Inc.: AAR</option>
<option value="19044">Chitina Air Service: CHI</option>
<option value="19045">Marco Island Airways Inc.: MRC</option>
<option value="19046">Caribbean Air Services Inc.: OHZ</option>
<option value="19047">Sundance Airlines: PRO</option>
<option value="19048">Seair Alaska Airlines Inc.: SAI</option>
<option value="19049">Southeast Airlines Inc.: SLZ</option>
<option value="19050">Alaska Aeronautical Indust.: AAZ</option>
<option value="19051">Imperial Airlines Inc.: IMP</option>
<option value="19052">Trans Western Airlines Utah: TWA</option>
<option value="19053">Wright Airlines Inc.: WRT</option>
<option value="19054">Presidential Express: COL</option>
<option value="19055">Mississippi Valley Airlines: MVA</option>
<option value="19056">Channel Flying Inc.: CHL</option>
<option value="19057">Rocky Mountain Airways Inc.: JCZ</option>
<option value="19058">Midstate Airlines Inc.: MIS</option>
<option value="19059">Sedalia Marshall Boonvl Stg: STG</option>
<option value="19060">Inlet Airlines: CKI</option>
<option value="19061">Command Airways Inc.: CMD</option>
<option value="19062">Emerald Airlines: EMA</option>
<option value="19063">Orion Air Inc.: ORI</option>
<option value="19064">Pan Am Express: RAN</option>
<option value="19065">Air Micronesia Inc.: AJ</option>
<option value="19066">Sunbird Inc.: SKI</option>
<option value="19067">Wings West Airlines: WWI</option>
<option value="19068">Southcentral Air Inc.: AND</option>
<option value="19069">Air Cargo Express Inc.: ACG</option>
<option value="19070">Associated Aviation Act.: AAA</option>
<option value="19071">Antilles Air Boats Inc.: AAB (1)</option>
<option value="19072">AAA Airlines: AAE</option>
<option value="19073">Argosy Air Lines Inc.: AAL</option>
<option value="19074">Air Bahia: ABH</option>
<option value="19075">Airbama Incorporated: ABI</option>
<option value="19076">Aeronaves Boringuena Inc.: ABO</option>
<option value="19077">Alaska Central Airways Inc.: ACA</option>
<option value="19078">Island Airlines Hawaii Inc.: ACH</option>
<option value="19079">AAA-Action Air Carrier Inc.: ACI</option>
<option value="19080">Air Cargo Enterprises Inc.: ACO</option>
<option value="19081">Air Chaparral Inc.: ACP</option>
<option value="19082">Alamo Commuter Airlines: ACS</option>
<option value="19083">Air Central Inc. (1): ACT</option>
<option value="19084">Air Central Inc.: ACK</option>
<option value="19085">Astec Air East Inc.: AEC</option>
<option value="19086">American Flag Airlines Inc.: AFA</option>
<option value="19087">Air Cargo America Inc.: AGA</option>
<option value="19088">All Island Air: AIA</option>
<option value="19089">Air Express Inc.: AIE</option>
<option value="19090">Air Mont. Inc.: AIM</option>
<option value="19091">Air Indiana: AIN</option>
<option value="19092">Air-Lift Associates Inc.: ALE</option>
<option value="19093">Brandt Air: ALI</option>
<option value="19094">All Seasons Air Pacific: ALL</option>
<option value="19095">North American Airlines Inc.: AMA</option>
<option value="19096">American Inter-Island Inc.: AMI</option>
<option value="19097">Air Nebraska Inc.: ANB</option>
<option value="19098">Airways Of New Mexico Inc.: ANM</option>
<option value="19099">Metro Air Northeast Vermont: ANO</option>
<option value="19100">Air North/Nenana: ANT</option>
<option value="19101">Trans New York: AOI</option>
<option value="19102">Arizona Pacific Inc.: API</option>
<option value="19103">Appalachian Flying Service: APL</option>
<option value="19104">Air Polynesia Inc.: APY</option>
<option value="19105">Arizona Aero Corp.: ARI</option>
<option value="19106">Arnold Aviation: ARN</option>
<option value="19107">Air Oregon: ARO</option>
<option value="19108">Arrowhead Airways Inc.: ARR</option>
<option value="19109">Amistad Airlines: ASD</option>
<option value="19110">Alpine Air Services Inc.: ASI</option>
<option value="19111">Asap Air Inc.: ASP</option>
<option value="19112">Astro Airways: AST</option>
<option value="19113">Air Atlantic Airlines Inc.: ATN</option>
<option value="19114">Pacific National Airways: ATO</option>
<option value="19115">Atlantis Airlines Inc.: ATS</option>
<option value="19116">Aerotransit Inc.: ATT</option>
<option value="19117">Air Carolina: ATX</option>
<option value="19118">Air Vectors Airways: AVA</option>
<option value="19119">Aero Virgin Islands Corp.: AVI</option>
<option value="19120">Aviation Services: AVS</option>
<option value="19121">Southern Jersey Airways: AVZ</option>
<option value="19122">Business Aircraft Corp.: BAC</option>
<option value="19123">Brennan & Hargreaves Inc.: BAH</option>
<option value="19124">Bankair Inc.: BAK</option>
<option value="19125">Bard-Air Corp.: BAR</option>
<option value="19126">Baja Cortez Airlines: BCA</option>
<option value="19127">Bennington Aviation Inc.: BEN</option>
<option value="19128">Beyer Aviation: BEY</option>
<option value="19129">Blackhawk Airways Inc.: BHK</option>
<option value="19130">Bighorn Airways Inc.: BHO</option>
<option value="19131">Birchwood Air Service: BIR</option>
<option value="19132">Bremerton Aviation Inc.: BMT</option>
<option value="19133">Boise Air Service: BOA</option>
<option value="19134">Brower Airways Inc.: BRO</option>
<option value="19135">Burlington Airways Inc.: BUR</option>
<option value="19136">Coleman Air Transport: CAC</option>
<option value="19137">Crawford Aviation Inc.: CAI</option>
<option value="19138">C & M Airlines: CAM</option>
<option value="19139">Metro Air Northeast N Y: CAP</option>
<option value="19140">Catalina Airlines Inc.: CAT</option>
<option value="19141">Air Virginia: CAV</option>
<option value="19142">Carriba Air Inc.: CBA</option>
<option value="19143">Cen-Tex Airlines Inc.: CEN</option>
<option value="19144">Century Airlines (Cal): CET</option>
<option value="19145">Chandler Flyer: CHD</option>
<option value="19146">Charter Airlines: CHE</option>
<option value="19147">Hammonds Commuter Air Serv.: CHF</option>
<option value="19148">Choi Aviation Inc.: CHO</option>
<option value="19149">Christman Air System: CHS</option>
<option value="19150">Cal Sierra Airlines: CIS</option>
<option value="19151">Centennial Airlines: CNN</option>
<option value="19152">Cotton Belt Aviation Inc.: COB</option>
<option value="19153">Coker Aviation Inc.: COK</option>
<option value="19154">Commutair: COM</option>
<option value="19155">Coral Air Inc.: COR</option>
<option value="19156">Cosmopolitan Comm. Airline: COS</option>
<option value="19157">Southeastern Commuter: COT</option>
<option value="19158">Courtesy Air Service Inc.: COU</option>
<option value="19159">Capitol Air Lines: CPA</option>
<option value="19160">Coastal Plains Commuter Inc.: CPC</option>
<option value="19161">Commuter Airlines: CRA</option>
<option value="19162">Crown Aviaiton Inc.: CRN</option>
<option value="19163">Crown Airways Inc.: CRO</option>
<option value="19164">Crested Butte Air Service: CRT</option>
<option value="19165">Catskill Airways Inc.: CSK</option>
<option value="19166">Century Airlines: CTA</option>
<option value="19167">Cothron Aviation: CTH</option>
<option value="19168">Catalina-Vegas Airlines: CVA</option>
<option value="19169">Danbury Airlines: DAN</option>
<option value="19170">Downeast Airlines Inc.: DEA</option>
<option value="19171">Decatur Aviation: DEC</option>
<option value="19172">DHL Airlines Inc.: DHL</option>
<option value="19173">Dickman Aviation Services: DIC</option>
<option value="19174">Desert Pacific Airways: DPA</option>
<option value="19175">Desert Pacific Airlines Inc.: DPI</option>
<option value="19176">Desert Airlines: DST</option>
<option value="19177">Executive Aviation Inc.: EAI</option>
<option value="19178">Eastern Caribbean Airways: EAS</option>
<option value="19179">Eastern Carolina Aviation: ECI</option>
<option value="19180">Ede Aire: EDE</option>
<option value="19181">Executive Four Winds: EFA</option>
<option value="19182">Eagle Commuter Airlines Inc.: EGL</option>
<option value="19183">East Hampton Aire Inc.: EHA</option>
<option value="19184">East. Indiana Aviation Sale: EIA</option>
<option value="19185">Air Pacific Inc.: EKA</option>
<option value="19186">Erie Airways Inc.: ERI</option>
<option value="19187">Empire Aero Service: ERO</option>
<option value="19188">Evanston Aviation: EVA</option>
<option value="19189">Federal Armored Service Inc.: FAR</option>
<option value="19190">Young Flying Service: FBI</option>
<option value="19191">Southern Airlines Inc.: FCA</option>
<option value="19192">Florida Airlines Inc.: FDA</option>
<option value="19193">Freedom Airlines Inc.: FDM</option>
<option value="19194">Flamenco Airways Inc.: FLM</option>
<option value="19195">Ford-Aire Inc.: FOR</option>
<option value="19196">Foster Aviation: FOS</option>
<option value="19197">Skycraft Inc.: FVA</option>
<option value="19198">Far West Airlines: FWA</option>
<option value="19199">General Aviation Inc.: GAS</option>
<option value="19200">Gromer Aviation Inc.: GAV</option>
<option value="19201">Central States Airline: GBA</option>
<option value="19202">Golden Carriage Aire: GCA</option>
<option value="19203">Midway Commuter: GCS</option>
<option value="19204">Green Hills Aviation Ltd.: GHA</option>
<option value="19205">Green Mountain Airlines Ltd.: GMA</option>
<option value="19206">Copper State Airlines: GOF</option>
<option value="19207">Isle Royale Seaplane Serv.: GRO</option>
<option value="19208">Golden South Airlines Inc.: GSL</option>
<option value="19209">Gull Air Inc.: GUL</option>
<option value="19210">Gunnel Aviation Inc.: GUN</option>
<option value="19211">Ross Aviation Inc.: GWE</option>
<option value="19212">Heussler Air Service Corp: HEU</option>
<option value="19213">Hensley Flying Service Inc.: HFS</option>
<option value="19214">Long Island Airlines: HMZ</option>
<option value="19215">Holiday Airlines Inc.: HOL</option>
<option value="19216">Iowa Airlines: HOR</option>
<option value="19217">Pacific Coast Airlines: HPZ</option>
<option value="19218">Trans-National Airlines Haw: HRA</option>
<option value="19219">Scenic Airlines Inc.: HSZ</option>
<option value="19220">Skystream Airlines: HUB</option>
<option value="19221">Hawking Corporation: HWK</option>
<option value="19222">Hyannis Aviation: HYA</option>
<option value="19223">Iowa City Flying Service: ICF</option>
<option value="19224">Idee Industries Inc.: III</option>
<option value="19225">Inland Empire Airlines Inc.: INA</option>
<option value="19226">Indiana Airways Inc. (Pa): IND</option>
<option value="19227">Indo-Pacific International: IPI</option>
<option value="19228">Island Airlines: ISL</option>
<option value="19229">Sunbelt Airlines Inc.: JAM</option>
<option value="19230">Air Chico: JCM</option>
<option value="19231">Jer-Don Air: JER</option>
<option value="19232">Knight Airlines Inc.: KAI</option>
<option value="19233">Key Airlines: KEE</option>
<option value="19234">Crown Air: KWZ</option>
<option value="19235">Chaparral Airlines Inc.: KXZ</option>
<option value="19236">Lancer Aviation Inc.: LAN</option>
<option value="19237">Lawrence Aviation: LAW</option>
<option value="19238">Havasu Airlines: LHA</option>
<option value="19239">Lakeland Aviation: LLA</option>
<option value="19240">Aero Commuter: LOS</option>
<option value="19241">Las Vegas Airlines: LVA</option>
<option value="19242">Magum Airlines: MAG</option>
<option value="19243">The Maui Commuter: MAI</option>
<option value="19244">Marshall's Air Inc.: MAR</option>
<option value="19245">Maxair Inc.: MAX</option>
<option value="19246">Mid Continental Airlines In: MCO</option>
<option value="19247">Metro Airlines: MDU</option>
<option value="19248">Metroplex Airlines: MET</option>
<option value="19249">Midway Aviation Inc.: MIY</option>
<option value="19250">Miller Air Transportersinc: MLL</option>
<option value="19251">Ocean Airways Inc.: MMH</option>
<option value="19252">Cumberland Airlines: MNZ</option>
<option value="19253">Merrimack Aviation Inc.: MRR</option>
<option value="19254">Midwest Aviation: MST</option>
<option value="19255">Arkansas Traveler Airline: MTA</option>
<option value="19256">Metroflight Airlines: MTR</option>
<option value="19257">National Air Commuter Inc.: NAC</option>
<option value="19258">New Born Wings Inc.: NEB</option>
<option value="19259">Nor East Commuter Airlines: NEC</option>
<option value="19260">Nevada Airlines: NEV</option>
<option value="19261">Northern Eagle Airways Inc.: NGL</option>
<option value="19262">Newair Flight Inc.: NHA</option>
<option value="19263">N. J. Merrimack Airlines: NJA</option>
<option value="19264">E. J. A. Newport Inc.: NPT</option>
<option value="19265">Northaire: NTH</option>
<option value="19266">Lake State Airways: NUM</option>
<option value="19267">New York Helicopter Corp.: NYH</option>
<option value="19268">Harbor Airlines Inc.: OAK</option>
<option value="19269">Ocean Reef Airways Inc.: OCR</option>
<option value="19270">Offshore Logistics: OFF</option>
<option value="19271">Omaha Aviation: OHA</option>
<option value="19272">Corporate Air Inc.: OIZ</option>
<option value="19273">Omak Aviation Airlines: OMK</option>
<option value="19274">Omni Pacific Airline: OMN</option>
<option value="19275">Sun Aire Lines: OOZ</option>
<option value="19276">Air Kentucky Air Lines: OWS</option>
<option value="19277">Permian Airways Inc.: PAI</option>
<option value="19278">Provincetown Boston: PBA</option>
<option value="19279">Piasa Commuter Airlines: PCA</option>
<option value="19280">Trans Southern Airways: PDA</option>
<option value="19281">Pearson Aircraft: PEA</option>
<option value="19282">Air Pennsylvania: PER</option>
<option value="19283">Petro Aviation Corp.: PET</option>
<option value="19284">Phillips Airlines: PHL</option>
<option value="19285">Phoenix Airlines: PHX</option>
<option value="19286">Pacific Island Airways: PIA</option>
<option value="19287">Planes Inc.: PLA</option>
<option value="19288">Polar Airways Inc.: PLZ</option>
<option value="19289">Pacific Missionary Aviation: PMA</option>
<option value="19290">Pioneer Airways: PNR</option>
<option value="19291">Pocono Airlines Inc.: POC</option>
<option value="19292">Pompano Airways: POM</option>
<option value="19293">Ponderosa Aviation Inc.: PON</option>
<option value="19294">Princeton Aviation Corp: PRA</option>
<option value="19295">Pro Air Services: PRR</option>
<option value="19296">Precision Valley Aviation: PVA</option>
<option value="19297">Bar Harbor Airways: QOZ</option>
<option value="19298">Royal-Air Ltd.: RAL</option>
<option value="19299">Realwest Airlines: REA</option>
<option value="19300">Aerosun International Airlines Inc.: RED</option>
<option value="19301">Royal Hawaiian Airways Inc.: RHA</option>
<option value="19302">Richardson Aviation: RIC</option>
<option value="19303">Indiana Airways Inc. (Reid: RID</option>
<option value="19304">Rio Airways Inc.: RIO</option>
<option value="19305">Riverside Air Service: RIV</option>
<option value="19306">Michigan Airways Inc.: RJS</option>
<option value="19307">Roederer Aviation Inc.: ROE</option>
<option value="19308">Royal American Airways Inc.: ROY</option>
<option value="19309">Air Rovers Inc.: RWG</option>
<option value="19310">Sajen Air Inc.: SAJ</option>
<option value="19311">Samoan Airlines Inc.: SAM</option>
<option value="19312">Air Cortez International: SAS</option>
<option value="19313">Air Americana: SAX</option>
<option value="19314">Saber Aviation Inc.: SBA</option>
<option value="19315">Suburban Airlines: SBN</option>
<option value="19316">Seaco Airlines Inc.: SCO</option>
<option value="19317">Skyline Airlines: SCT</option>
<option value="19318">South Coast Airways: SCY</option>
<option value="19319">Semo Aviation Inc.: SEM</option>
<option value="19320">Stahmannfarms Inc.: SFI</option>
<option value="19321">Sfo Helicopter Airlines Inc.: SFO</option>
<option value="19322">Sierra Flite Service Inc.: SFS</option>
<option value="19323">Shasta Air Inc.: SHS</option>
<option value="19324">Shavano Air Inc.: SHV</option>
<option value="19325">Silver State Airlines: SIA</option>
<option value="19326">San Juan Airlines Inc.: SJA</option>
<option value="19327">Bas Airlines: SKL</option>
<option value="19328">Scheduled Skyways: SKM</option>
<option value="19329">Stopher Mechanical Inc.: SMC</option>
<option value="19330">Gelco Courier Services Inc.: SNC</option>
<option value="19331">Shawnee Airlines: SNE</option>
<option value="19332">Mall Airways Inc.: SOA</option>
<option value="19333">Soonair Lines Inc.: SOL</option>
<option value="19334">Springfield Air Service: SPF</option>
<option value="19335">Sterling Air Service: SRL</option>
<option value="19336">Southern Seaplane: SSP</option>
<option value="19337">Sierra Express Inc.: SSS</option>
<option value="19338">Seaplane Shuttle Transport: SST</option>
<option value="19339">Trans East International: STF</option>
<option value="19340">Star Aviation Corporation: STR</option>
<option value="19341">Sun International Airways: SUI</option>
<option value="19342">Sunbelt: SUT</option>
<option value="19343">Sun Valley Airlines: SVL</option>
<option value="19344">Sunwest Airlines: SWA</option>
<option value="19345">Air Colorado: TAC</option>
<option value="19346">Tejas Airlines Inc.: TAL</option>
<option value="19347">Yosemite Airlines Inc.: TAS</option>
<option value="19348">Trans Catalina Airlines: TCA</option>
<option value="19349">Oceanair Line: TCE</option>
<option value="19350">Trans California Airlines: TCI</option>
<option value="19351">Trans-Central Airlines Inc.: TCL</option>
<option value="19352">Trans-Colorado Airlines: TCO</option>
<option value="19353">Tennessee Airways Inc.: TEN</option>
<option value="19354">Terre Haute Air Commuter: TER</option>
<option value="19355">Thorson Aviation: THO</option>
<option value="19356">Trans Air Inc.: TIA</option>
<option value="19357">Skyfreight: TIS</option>
<option value="19358">Trans Mo Airlines: TMA</option>
<option value="19359">Transtate Aviation: TNS</option>
<option value="19360">Trans Pennsylvania Airlines: TRP</option>
<option value="19361">Trans Sierra Airlines Inc.: TSI</option>
<option value="19362">Tulsair Beechcraft Inc.: TUL</option>
<option value="19363">Temsco Airlines: TYE</option>
<option value="19364">Universal Airways Inc.: UAI</option>
<option value="19365">Air U.S.: USA</option>
<option value="19366">Vagabond Aviation Inc.: VAG</option>
<option value="19367">Britt Airlines Inc.: VER</option>
<option value="19368">Viking Express: VIG</option>
<option value="19369">Vale International Airlines: VIN</option>
<option value="19370">Valley Airlines: VLY</option>
<option value="19371">Air East Airlines: WAC</option>
<option value="19372">Walker's International: WCA</option>
<option value="19373">Mountainwest Airlines: WCI</option>
<option value="19374">Western Star Airlines Inc.: WES</option>
<option value="19375">Western Charter Inc.: WET</option>
<option value="19376">Wheeler Airlines: WFS</option>
<option value="19377">Wisc Air: WIA</option>
<option value="19378">Will's Air: WIL</option>
<option value="19379">Wings Airways: WNG</option>
<option value="19380">Mcphillips Flying Service: ZFZ</option>
<option value="19381">Air New Mexico: ZIA</option>
<option value="19382">Winnipesaukee Aviation Inc.: ZMZ</option>
<option value="19383">Skyway Aviation Inc.: ZYZ</option>
<option value="19384">P.S. Air Freight Inc.: PSA</option>
<option value="19385">Reeve Aleutian Airways Inc.: RV (1)</option>
<option value="19386">Northwest Airlines Inc.: NW</option>
<option value="19387">Wien Air Alaska Inc.: WC</option>
<option value="19388">Southern Airways: FTI</option>
<option value="19389">Air Florida Inc.: QH</option>
<option value="19390">Air California Inc.: OC</option>
<option value="19391">Pacific Southwest Airlines: PS (1)</option>
<option value="19392">Rich International Airways: RIQ</option>
<option value="19393">Southwest Airlines Co.: WN</option>
<option value="19394">Mid-South Aviation Inc.: VL</option>
<option value="19395">Mid-South Aviation Inc. (1): RCA</option>
<option value="19396">Sky West Aviation Inc.: QG</option>
<option value="19397">Republic Airlines Inc.: RC</option>
<option value="19398">Dauphin Island Airways: DAU</option>
<option value="19399">New York Air Inc.: NY</option>
<option value="19400">Global International Airways Corp.: GIQ</option>
<option value="19401">Colgan Airways Inc.: CJ</option>
<option value="19402">Overseas National Airways: UNQ</option>
<option value="19403">Flight International: PTQ</option>
<option value="19404">Academy Airlines: ACD</option>
<option value="19405">Check-Air Inc.: ACL</option>
<option value="19406">Transwest Air Express: ACW</option>
<option value="19407">Airgo Inc.: AIG</option>
<option value="19408">American Air Transport: AMT</option>
<option value="19409">Bo-S-Aire Airlines Inc.: BOI</option>
<option value="19410">Combs Airways Inc.: CMB</option>
<option value="19411">Summit Airlines Inc.: DUZ</option>
<option value="19412">Eagle Aviation Inc.: EEZ</option>
<option value="19413">Falwell Aviation Inc.: FAA</option>
<option value="19414">Falcon Airways Inc.: FAC</option>
<option value="19415">Pinehurst Airlines Inc.: PHR</option>
<option value="19416">Great Western Airlines Inc.: ROS</option>
<option value="19417">Air Freight Express: RRT</option>
<option value="19418">S. S. Airways Inc.: SSA</option>
<option value="19419">Aero Union Corp: XAA</option>
<option value="19420">Air Express International Airlines: XAC</option>
<option value="19421">Central American International: XAJ</option>
<option value="19422">Michigan Peninsula Airways: XAT</option>
<option value="19423">WTC Airlines: XBF</option>
<option value="19424">Profit Airlines Inc.: XBH</option>
<option value="19425">CF Air Freight: XBI</option>
<option value="19426">International Air Service: XBJ</option>
<option value="19427">Aeronaves De Puerto Rico: XBQ</option>
<option value="19428">Allstates Air Cargo Inc.: XBR</option>
<option value="19429">Cam Air International Inc.: XAQ</option>
<option value="19430">Purolator Sky Courier Inc.: XAZ</option>
<option value="19431">Circle Airfreight Corp.: XBP</option>
<option value="19432">Pacific Alaska Airlines Inc.: XBT</option>
<option value="19433">Icb International Airlines: XBX</option>
<option value="19434">Cohlmia Aviation: XAM</option>
<option value="19435">Amerford Airways Inc.: XAE</option>
<option value="19436">Astro-Wing Airlines Inc.: XAF</option>
<option value="19437">Ball Brothers Inc.: XAG</option>
<option value="19438">Burlington Northern Inc.: XAI</option>
<option value="19439">Century Airlines Inc.: XAK</option>
<option value="19440">Dallas Flight Center: XAO</option>
<option value="19441">Jet Way Inc.: XAR</option>
<option value="19442">Klondike Air Inc.: XAS</option>
<option value="19443">Pat Air: XAY</option>
<option value="19444">Phh Air Inc.: XBM</option>
<option value="19445">Flight Line Inc.: XAU</option>
<option value="19446">Viking International Airlines Inc.: CGL</option>
<option value="19447">Capitol International Inc.: CL</option>
<option value="19448">Air Caravane Inc.: AEQ</option>
<option value="19449">Argo S. A.: AGQ</option>
<option value="19450">Norontair: AIQ</option>
<option value="19451">Alberta Northern Airlines: ALQ</option>
<option value="19452">Aviacion Y Comercio S.A.: AO</option>
<option value="19453">Air Bvi Limited: BLQ</option>
<option value="19454">Spantax S. A.: BXQ</option>
<option value="19455">Dan Air Services: DA</option>
<option value="19456">Maersk Air I/S: DM</option>
<option value="19457">Aerolineas Dominicanas S A: DOQ</option>
<option value="19458">Caribwest Airways Ltd.: DQQ</option>
<option value="19459">Execaire Aviation Ltd.: EBQ</option>
<option value="19460">Aero Trades (Western) Ltd.: ERQ</option>
<option value="19461">Fast Air Carrier Ltd. (1): FAQ</option>
<option value="19462">Business Flights Ltd.: HIQ</option>
<option value="19463">Tar Airlines: HRQ</option>
<option value="19464">Transavia Holland B. V.: HVQ</option>
<option value="19465">Iscargo Hf: ICQ</option>
<option value="19466">Tradewinds Airways Ltd.: IKQ</option>
<option value="19467">Aerlinte Eireann Teoranta: IN</option>
<option value="19468">Iran National Airlines Corp: IR</option>
<option value="19469">Inair: IXQ</option>
<option value="19470">Allarco Developments Ltd.: JXQ</option>
<option value="19471">Transmeridian Air Cargo Ltd.: KKQ</option>
<option value="19472">Kelowna Flightcraft Air Cha: KWQ</option>
<option value="19473">Liat (1974) Limited: LIQ</option>
<option value="19474">Millardair Limited: MAQ</option>
<option value="19475">Montana Austria Flugetrieb: MGQ</option>
<option value="19476">P.N. Merpati Nusantara Air.: MZ</option>
<option value="19477">North Cariboo Flying Serv.: NFQ</option>
<option value="19478">Norcanair: NKQ</option>
<option value="19479">Northward Airlines Ltd.: NN</option>
<option value="19480">North Coast Air Services: NSQ</option>
<option value="19481">National Aviation Consult.: NTQ</option>
<option value="19482">Air Niugini: NUQ</option>
<option value="19483">Nunasi-Central Airlines Ltd.: ONQ</option>
<option value="19484">Ontario Worldair Limited: OWQ</option>
<option value="19485">Pem-Air Limited: PD (1)</option>
<option value="19486">Eastern Provincial Airways: PV</option>
<option value="19487">Pacific Western Airlines: PW</option>
<option value="19488">Inter-Quebec (Intair): QB</option>
<option value="19489">Syrian Arab Airlines: RB</option>
<option value="19490">Aerotransportes Entre Rios: RSQ</option>
<option value="19491">Redcoat Air Cargo Limited: RY</option>
<option value="19492">Skycharter (Malton) Ltd.: SJQ</option>
<option value="19493">Superior Airways Limited: SSQ</option>
<option value="19494">Belize Airways Limited: ST</option>
<option value="19495">Skycraft Air Transport Inc.: STQ</option>
<option value="19496">Trans-Mediterranean Airways: TLQ</option>
<option value="19497">British Caribbean Airways: TXQ</option>
<option value="19498">Air Manila Inc.: UMQ</option>
<option value="19499">Avalon Aviation Ltd.: VOQ</option>
<option value="19500">Wardair Canada Inc.: WDQ</option>
<option value="19501">Gateway Aviation Limited: WGQ</option>
<option value="19502">Windward Islands Airways: WM</option>
<option value="19503">Nal Inc.: XBV</option>
<option value="19504">Yellow Bird Air: YBQ</option>
<option value="19505">Air Europe Limited: AE</option>
<option value="19506">Intair: ND</option>
<option value="19507">Yugoslav Airlines: JU (1)</option>
<option value="19508">Union De Transports Aeriens: UT</option>
<option value="19509">Air Haiti S. A.: HJ</option>
<option value="19510">Servicio Aereo De Honduras: SH</option>
<option value="19511">Sterling Airways A/S: NBQ</option>
<option value="19512">Aerolineas El Salvador S A: SZQ</option>
<option value="19513">Transp. Aereos Bolivianos: BOQ</option>
<option value="19514">Aeronaves Del Peru: ADQ</option>
<option value="19515">Compania Dominicana De Avia: DO</option>
<option value="19516">Nigeria Airways Ltd.: WT</option>
<option value="19517">Lineas Aereas Paraguayas: PZ</option>
<option value="19518">Lufthansa Cargo Airlines: GE</option>
<option value="19519">Venezuelan International Airways: VA (1)</option>
<option value="19520">Andes: ED</option>
<option value="19521">Compan. De Aviacion Faucett: CF</option>
<option value="19522">Aviateca: GU</option>
<option value="19523">Canadian Airlines International Ltd.: CP (1)</option>
<option value="19524">Guyana Airways Corporation: GY</option>
<option value="19525">Seagreen Air Transport: ESQ</option>
<option value="19526">Air Nauru: ON</option>
<option value="19527">Aero Peru: PL</option>
<option value="19528">Balair Ag: BBQ</option>
<option value="19529">Sabena Belgian World Air.: SN (1)</option>
<option value="19530">Air Afrique: RK</option>
<option value="19531">Air Canada: AC</option>
<option value="19532">Compagnie Natl Air France: AF</option>
<option value="19533">National Aviation Company of India Limited d/b/a Air India: AI</option>
<option value="19534">Aeromexico: AM</option>
<option value="19535">Aerolineas Argentinas: AR</option>
<option value="19536">Royal Air Maroc: AT</option>
<option value="19537">Aerovias Nacl De Colombia: AV</option>
<option value="19538">Finnair Oy: AY</option>
<option value="19539">Compagnia Aerea Italiana: AZ</option>
<option value="19540">British Airways Plc: BA</option>
<option value="19541">British Midland Airways Ltd.: BD</option>
<option value="19542">Caribbean Airlines Limited: BW</option>
<option value="19543">Air China: CA</option>
<option value="19544">China Airlines Ltd.: CI</option>
<option value="19545">Cargolux Airlines International S.A: CV</option>
<option value="19546">Icelandair: FI</option>
<option value="19547">Iberia Air Lines Of Spain: IB</option>
<option value="19548">Japan Air Lines Co. Ltd.: JL</option>
<option value="19549">Air Jamaica Limited: JM</option>
<option value="19550">Korean Air Lines Co. Ltd.: KE</option>
<option value="19551">Klm Royal Dutch Airlines: KL</option>
<option value="19552">Lan-Chile Airlines: LA</option>
<option value="19553">Lloyd Aereo Boliviano S. A.: LB</option>
<option value="19554">Lufthansa German Airlines: LH</option>
<option value="19555">Polskie Linie Lotnicze: LO</option>
<option value="19556">Lacsa: LR</option>
<option value="19557">Luftransport-Unternehmen: LT</option>
<option value="19558">El Al Israel Airlines Ltd.: LY</option>
<option value="19559">Compania Mexicana De Aviaci: MX</option>
<option value="19560">N. W. Territorial Airways: NWQ</option>
<option value="19561">Olympic Airways: OA</option>
<option value="19562">Polynesian Airlines Ltd.: PH</option>
<option value="19563">Pakistan International Airlines: PK</option>
<option value="19564">Philippine Airlines Inc.: PR</option>
<option value="19565">Surinam Airways Limited: PY</option>
<option value="19566">Qantas Airways Ltd.: QF</option>
<option value="19567">Varig S. A.: RG</option>
<option value="19568">Alia-(The) Royal Jordanian: RJ</option>
<option value="19569">Tarom Romanian Air Transpor: RO</option>
<option value="19570">South African Airways: SA</option>
<option value="19571">Scandinavian Airlines Sys.: SK</option>
<option value="19572">Singapore Airlines Ltd.: SQ</option>
<option value="19573">Aeroflot Russian Airlines: SU</option>
<option value="19574">Taca International Airlines: TA</option>
<option value="19575">Thai Airways International Ltd.: TG</option>
<option value="19576">Tap-Portuguese Airlines: TP</option>
<option value="19577">Bahamasair Holding Limited: UP</option>
<option value="19578">Transtar Airlines Corp.: MC</option>
<option value="19579">Heavylift Cargo Airlines Lt: HLQ</option>
<option value="19580">Ladeco: UC</option>
<option value="19581">Altus Airlines: ALT</option>
<option value="19582">Atlantic Air: ANC</option>
<option value="19583">Aero International Airlines: BAA</option>
<option value="19584">Northern Star: DIR</option>
<option value="19585">Skytrain: SKT</option>
<option value="19586">Trans Air Cargo Inc.: TGO</option>
<option value="19587">T-Bird Air Inc.: THQ</option>
<option value="19588">Royal West Airways Inc.: ROA</option>
<option value="19589">Air East Of Delaware Inc.: AED</option>
<option value="19590">Atlanta Express: ALX</option>
<option value="19591">Air New Orleans: AOR</option>
<option value="19592">Air Vermont Inc.: AVR</option>
<option value="19593">Dolphin Airways Inc.: DOL</option>
<option value="19594">Devoe Airlines: DVO</option>
<option value="19595">Golden Pacific Airlines: KIN</option>
<option value="19596">National Florida Airlines: NFA</option>
<option value="19597">Slocum Air Inc.: SLO</option>
<option value="19598">State Airlines Inc.: STA</option>
<option value="19599">Air Molakai: TRO</option>
<option value="19600">Williams Air Inc.: WIR</option>
<option value="19601">Mission Air: WSU</option>
<option value="19602">Guy-America Airways Inc.: HX (1)</option>
<option value="19603">Pacific Express: VB (1)</option>
<option value="19604">Northeastern International Airways: QS (1)</option>
<option value="19605">Friendship Air Alaska: HAR</option>
<option value="19606">Minuteman Aviation Inc.: MIN</option>
<option value="19607">Virgin Islands Seaplane: VIS</option>
<option value="19608">Flying Tiger Line Inc.: FT</option>
<option value="19609">Aerocondor: OD (1)</option>
<option value="19610">Emerald Airlines Inc.: OD</option>
<option value="19611">Northern Airlines Inc.: NRN</option>
<option value="19612">Pacific East Air Inc.: 6P</option>
<option value="19613">Jet Charter Service Inc.: TJ</option>
<option value="19614">Aeroservicios Ecuatorianos: EOQ</option>
<option value="19615">Arista International Airlines Inc.: RAQ</option>
<option value="19616">Kuwait Airways Corp.: KU</option>
<option value="19617">Burlington Aeroplane Co.: BAY</option>
<option value="19618">Desert Sun Airlines: DSA</option>
<option value="19619">Lake Union Air Service: LAS</option>
<option value="19620">Aer Turas Teoranta: QTQ</option>
<option value="19621">Aero B Venezuela C.A.: AFQ</option>
<option value="19622">Air Ontario Limited: GX</option>
<option value="19623">Aer Lingus Plc: EI</option>
<option value="19624">Saudi Arabian Airlines Corp: SV</option>
<option value="19625">Air Polynesia d/b/a DHL Cargo: XAB</option>
<option value="19626">Air Natl Aircraft Sal & Ser: XBZ</option>
<option value="19627">A/S Conair: CIQ</option>
<option value="19628">Dash Air Corporation: ANI</option>
<option value="19629">Air Resorts Airlines: ARA</option>
<option value="19630">Manu'a Air Transport: MUA</option>
<option value="19631">Pacific Cal Air: PCL</option>
<option value="19632">Service Aviation Inc.: SER</option>
<option value="19633">The Time Machine: TTM</option>
<option value="19634">Servicio De Carga Aerea Sa: CMQ</option>
<option value="19635">Hapag Lloyd Flug.: HAQ</option>
<option value="19636">Air One Inc.: CB</option>
<option value="19637">Middle East Airlines S.A.L.: ME</option>
<option value="19638">Arcata Flying Service: AFS</option>
<option value="19639">Grand Canyon Airlines: GRD</option>
<option value="19640">Kodiak Airways Inc.: KOD</option>
<option value="19641">Mid-Atlantic Exp. Airlines: MAE</option>
<option value="19642">National Commuter Airlines: NCA</option>
<option value="19643">Sundorph Aeronautical Corp.: SAC</option>
<option value="19644">Waring Air: WAR</option>
<option value="19645">All Star Airlines Inc.: EP</option>
<option value="19646">Aeron International Airlines Inc.: AXQ</option>
<option value="19647">Jet Fleet Intl. Airlines: JIQ</option>
<option value="19648">Markair Express: HER</option>
<option value="19649">Alaska Island Air Inc.: LSZ</option>
<option value="19650">Air Sunshine Inc.: AAT</option>
<option value="19651">Eastman Airways Inc.: EAT</option>
<option value="19652">Spirit Helicopter: SPH</option>
<option value="19653">Air National: AHQ</option>
<option value="19654">Executive Charter: EXC (1)</option>
<option value="19655">Aviation Associates: SNA</option>
<option value="19656">Airmarc Airlines Inc.: ARM</option>
<option value="19657">Panorama Air Tours: PAT</option>
<option value="19658">Trans-Air-Link Corporation: TKQ</option>
<option value="19659">Audi Air Inc.: AAI</option>
<option value="19660">Galaxy Airlines Inc.: GAQ</option>
<option value="19661">Intl Air Service Co. Ltd.: IDQ</option>
<option value="19662">Transbrasil S.A.: TR (1)</option>
<option value="19663">Hawkins And Powers Aviation: XCA</option>
<option value="19664">Jet East Inc.: XBC</option>
<option value="19665">Air Sedona: ARS</option>
<option value="19666">Caribbean Express Inc.: CRE</option>
<option value="19667">Tri-State Airlines Inc.: TFZ</option>
<option value="19668">Frontier Horizon Inc.: FH</option>
<option value="19669">Aermediterranea S.P.A.: AWQ</option>
<option value="19670">Markair Inc.: BF</option>
<option value="19671">Air Tungaru Corporation: VK</option>
<option value="19672">Resort Airlines Inc.: RES</option>
<option value="19673">Alpine Air: AAV</option>
<option value="19674">Americair Inc.: AME</option>
<option value="19675">Airspur Helicopters Inc.: ARP</option>
<option value="19676">Silver Kris Services Ltd.: SKS</option>
<option value="19677">Buffalo Airways Inc.: BFQ</option>
<option value="19678">Aloha Airlines Inc.: AQ</option>
<option value="19679">Air Spirit Inc.: APS</option>
<option value="19680">Metro Express: EME</option>
<option value="19681">Frontier Commuter: FRT</option>
<option value="19682">Virgin Atlantic Airways: VS</option>
<option value="19683">Airmark Corporation: MKQ</option>
<option value="19684">Independent Air Inc.: INQ</option>
<option value="19685">Aerial Transit Company: TPQ</option>
<option value="19686">Westflight Aviation: WFT</option>
<option value="19687">Horizon Air: QX</option>
<option value="19688">Midway Express Airlines: 2M</option>
<option value="19689">St. Lucia Airways Limited: SDQ</option>
<option value="19690">Hawaiian Airlines Inc.: HA</option>
<option value="19691">Pacific Air Express Inc.: XDA</option>
<option value="19692">Trump Air: RIA</option>
<option value="19693">North Pacific Airlines Inc.: NPA</option>
<option value="19694">Flirite Inc.: FLR</option>
<option value="19695">Talarik Creek Air Taxi: TAT</option>
<option value="19696">Royale Airlines Inc.: RAY</option>
<option value="19697">Worldways Canada Ltd.: WWQ</option>
<option value="19698">Air Charter (Safa): AQQ</option>
<option value="19699">Samoa Airlines Inc.: MB</option>
<option value="19700">Alpha Air: APH</option>
<option value="19701">Jetaire Airlines Inc.: JTA</option>
<option value="19702">Haiti Air: KB</option>
<option value="19703">Harbor Air Service: HSV</option>
<option value="19704">Continental Air Lines Inc.: CO</option>
<option value="19705">Interstate Airlines Inc.: IRQ</option>
<option value="19706">Hawaii Pacific Helicopters: CLD</option>
<option value="19707">Eastern Air Lines Inc.: EA</option>
<option value="19708">Chisum Flying Service: CSM</option>
<option value="19709">AvAir: AMR</option>
<option value="19710">Armstrong Air Service Inc.: AAP</option>
<option value="19711">Eagle Airline: EGA</option>
<option value="19712">Business Express Airlines: BEA</option>
<option value="19713">Alliance Airlines: ACN</option>
<option value="19714">Astor Air: ASR</option>
<option value="19715">West Penn Commuter: BAT</option>
<option value="19716">Barken International: BRK</option>
<option value="19717">Commuter Airlines (Ca): CMR</option>
<option value="19718">Cresent Medivac: CRH</option>
<option value="19719">Coastal Air Transport: CTL</option>
<option value="19720">Exec Express: EEX</option>
<option value="19721">La Skycab Airline: LAA</option>
<option value="19722">National Air: NAT</option>
<option value="19723">Omniflight Airways: OMI</option>
<option value="19724">Southern Express Airways: SEP</option>
<option value="19725">Turner Aire: TUR</option>
<option value="19726">AAR Western Skyways: WSK</option>
<option value="19727">Skybus Inc.: FW</option>
<option value="19728">Caicos Caribbean Airways: CUQ</option>
<option value="19729">Jet Express: BDE</option>
<option value="19730">Regent Air Corporation: 4R</option>
<option value="19731">Westates Airlines: WTA</option>
<option value="19732">Action Airlines: AON</option>
<option value="19733">California Seaboard: CAF</option>
<option value="19734">Enterprise Airlines Inc.: ENT</option>
<option value="19735">Island Air Express: IEX</option>
<option value="19736">Maui Airlines: MAA</option>
<option value="19737">Metro Express 11: MEX</option>
<option value="19738">Otter Air: OTT</option>
<option value="19739">Prime Air Inc.: PRM</option>
<option value="19740">Sallee's Aviation: SAL</option>
<option value="19741">Wrangell Air Service: WGL</option>
<option value="19742">Atlantic Gulf Airlines: ZY</option>
<option value="19743">Skyworld Airlines Inc.: PKQ</option>
<option value="19744">Presidential Airways Inc.: XV</option>
<option value="19745">Caribbean Air Cargo Co Ltd.: DC</option>
<option value="19746">P.T. Garuda Indonesian Arwy: GA</option>
<option value="19747">Egyptair: MS</option>
<option value="19748">Bay Air: BYA</option>
<option value="19749">Five Star Airlines: FFQ</option>
<option value="19750">King Flying Service: KFS</option>
<option value="19751">Le Point Air: LEQ</option>
<option value="19752">Barrow Air: BRW</option>
<option value="19753">Big Island Air: BIA</option>
<option value="19754">Cityhop: CCA</option>
<option value="19755">GP Express Airlines: GPA</option>
<option value="19756">Iowa Airways: IOW</option>
<option value="19757">Mountain West Airlines: MWA</option>
<option value="19758">Resort Commuter: RSC</option>
<option value="19759">Texas National Airlines: TXA</option>
<option value="19760">Air Hawaii: AHC</option>
<option value="19761">Aerotal: XK</option>
<option value="19762">Air L.A.: ALS</option>
<option value="19763">Aero Coach: AEO</option>
<option value="19764">Air Link Airways: ALK</option>
<option value="19765">Million Air: BFG</option>
<option value="19766">Helitrans: HEL</option>
<option value="19767">La Helicopter: LAH</option>
<option value="19768">Omniflight Helicopters: OMH</option>
<option value="19769">Reeves Air: RVA</option>
<option value="19770">Compania Panamena (Copa): CM</option>
<option value="19771">Zas Airline Of Egypt: ZAQ</option>
<option value="19772">Polar International: POL</option>
<option value="19773">Hemisphere Air Charter: XDC</option>
<option value="19774">Airways International: AIT</option>
<option value="19775">Chicago Airlines: CGA</option>
<option value="19776">Royal West Airlines: YM</option>
<option value="19777">Airpac Inc.: XYZ</option>
<option value="19778">Aerovias Venezolanas-Avensa: VE</option>
<option value="19779">Cathay Pacific Airways Ltd.: CX</option>
<option value="19780">Galena Air Service: GAL</option>
<option value="19781">Stateswest Airlines: STW</option>
<option value="19782">Executive Transport: EXR</option>
<option value="19783">Propheter Aviation: PRP</option>
<option value="19784">Wise Airlines Inc.: WAI</option>
<option value="19786">Haines Airways: HNS</option>
<option value="19787">Great American Airways: FDQ</option>
<option value="19788">Air Puerto Rico Airlines: FD</option>
<option value="19789">Viacao Aerea Sao Paulo: VP</option>
<option value="19790">Delta Air Lines Inc.: DL</option>
<option value="19791">All Nippon Airways Co.: NH</option>
<option value="19792">International Parcel Express Inc.: XDD</option>
<option value="19793">Anglo Airlines Ltd.: AZQ</option>
<option value="19794">Midcontinent Airlines: MDC</option>
<option value="19795">Malaysian Airline System: MH</option>
<option value="19796">Pilgrim Aviation & Airlines: PMT</option>
<option value="19797">Florida Express Inc.: ZO</option>
<option value="19798">Orion Air: OPQ</option>
<option value="19799">Nationair: NAQ</option>
<option value="19800">Air Cape: APE</option>
<option value="19801">Lake Coastal: LCT</option>
<option value="19802">Mst Aviation: MTV</option>
<option value="19803">First Air: 7F</option>
<option value="19804">Transportes Aereos De Cabo: VR</option>
<option value="19805">American Airlines Inc.: AA</option>
<option value="19806">Air Charter Systems (Acs): WAQ</option>
<option value="19807">Helitac Aviation: HET</option>
<option value="19808">Belize Air International Ltd.: BM</option>
<option value="19809">Highland Express Airways: VY</option>
<option value="19810">Mid Pacific Airlines Inc.: MPA</option>
<option value="19811">Aero Tranportes Panamenos: ATQ</option>
<option value="19812">Millon Air Inc.: LBQ</option>
<option value="19813">Air Caribe International: ARB</option>
<option value="19814">Air South (1): ASU</option>
<option value="19815">Air South: ASH</option>
<option value="19816">Bangor International Air: BAN</option>
<option value="19817">Chester County Aviation: CCO</option>
<option value="19818">East Coast Airways: ECR</option>
<option value="19819">Hub Express: HEP</option>
<option value="19820">Tropical Helicopter Airways: THA</option>
<option value="19821">Turk Hava Yollari A.O.: TK</option>
<option value="19822">Piedmont Aviation Inc.: PI</option>
<option value="19823">Air Train Inc.: XDE</option>
<option value="19824">Haiti Air Freight Intl: HFQ</option>
<option value="19825">Ketchikan Air Service: KET</option>
<option value="19826">Salair Inc.: XDF</option>
<option value="19827">Npa Inc.: NAP</option>
<option value="19828">Air America: GM</option>
<option value="19829">Time Air Ltd.: KI</option>
<option value="19830">Nippon Cargo Airlines: KZ</option>
<option value="19831">Seagull Air Service: SEG</option>
<option value="19832">Nasville Eagle: NAS</option>
<option value="19833">Aleutian Air: ALU</option>
<option value="19834">Custom Air Service: CUS</option>
<option value="19835">GCS Air Service: GSC</option>
<option value="19836">Golden State Airlines: GST</option>
<option value="19837">Springdale Air: SPG</option>
<option value="19838">Sportsman Flying Service: SPR</option>
<option value="19839">Saeta Airlines: EH</option>
<option value="19840">Aerolineas Mundo: MUQ</option>
<option value="19841">Tropical Airways Inc.: GG (1)</option>
<option value="19842">Grenada Airways Ltd.: GG (2)</option>
<option value="19843">Mid Pacific Air Corp.: MPC</option>
<option value="19844">Exec Express II: EET</option>
<option value="19845">Taquan Air Service: TAQ</option>
<option value="19846">Chartair: CTR</option>
<option value="19847">Laredo Air: LAR</option>
<option value="19848">Qwest Commuter: QWE</option>
<option value="19849">Tri Air Freight: TAF</option>
<option value="19850">Wra Inc.: WRA</option>
<option value="19851">Zambia Airways Corp.: Q2</option>
<option value="19852">Swissair Transport Co. Ltd.: SR</option>
<option value="19853">Airlift International: ARD</option>
<option value="19854">Pacair: PCR</option>
<option value="19855">Bradley Air Services Ltd.: BCQ</option>
<option value="19856">Corse Air International: CYQ</option>
<option value="19857">Iraqi Airways: IA</option>
<option value="19858">Monarch Airlines: ZB</option>
<option value="19859">Vacationair: VAQ</option>
<option value="19860">Lineas Aereas La-Tur Sa: LUQ</option>
<option value="19861">Holidair Airways: HOQ</option>
<option value="19862">Aerovias S.A.: AOQ</option>
<option value="19863">Alas De Transporte International: APQ</option>
<option value="19864">Transamerica Airlines Inc.: TV (1)</option>
<option value="19865">Haiti Trans Air: TV</option>
<option value="19866">Canadian Aviation Express: CWQ</option>
<option value="19867">Japan Air System Co. Ltd.: JD (1)</option>
<option value="19868">Manhattan Express: MEA</option>
<option value="19869">Britannia Airways Ltd.: BY</option>
<option value="19870">Aero Freight: AEF</option>
<option value="19871">Panama Aviation: PNM</option>
<option value="19872">Welch Aviation: WLH</option>
<option value="19873">Austrian Airlines: OS</option>
<option value="19874">Air Transport International: 8C</option>
<option value="19875">Aero California: JR</option>
<option value="19876">Heritage Airlines: HRG</option>
<option value="19877">Kitty Hawk Air Cargo: XDH</option>
<option value="19878">Columbia Pacific Airlines (1): EXA</option>
<option value="19879">Columbia Pacific Airlines: CLB</option>
<option value="19880">Central States Air Lines: CSL</option>
<option value="19881">Mohawk Airlines: MHK</option>
<option value="19882">Skymaster: SYM</option>
<option value="19883">Novair International Airways Ltd.: NVQ</option>
<option value="19884">TPI International Airways: TSQ</option>
<option value="19885">Universal Airlines Inc.: UTQ</option>
<option value="19886">Aruba Cargo: IPQ</option>
<option value="19887">Latcr: LCQ</option>
<option value="19888">Transcarga: TDQ (1)</option>
<option value="19889">Venexcargo: TDQ</option>
<option value="19890">Aeroejecutivos C.A.: EJQ</option>
<option value="19891">Aeropuma: PUQ</option>
<option value="19892">Aeronautica De Cancun: ACQ</option>
<option value="19893">Aerovias Colombianas Arca: ARQ</option>
<option value="19894">Zuliana De Aviacion: ZUQ</option>
<option value="19895">Interamericana De Aviacion: ITQ</option>
<option value="19896">Fast Air Carrier Ltd.: UD</option>
<option value="19897">Lineas Aereas Mayas (Lamsa): MYQ</option>
<option value="19898">Emery Worldwide Airlines: TNQ</option>
<option value="19899">Hong Kong Dragonair: KA</option>
<option value="19900">Air Marshall Islands Inc.: CW</option>
<option value="19901">Blue Bell Inc.: BUQ (1)</option>
<option value="19902">Wrangler Aviation Inc.: BUQ</option>
<option value="19903">Conquest Airline Corp.: CQI</option>
<option value="19904">Air Southeast: ATH</option>
<option value="19905">California Air Shuttle: CLF</option>
<option value="19906">Northcoast Executive: NCE</option>
<option value="19907">Scott Aviation: SCN</option>
<option value="19908">Trans Air (Hawaii): TXE</option>
<option value="19909">Air Belgium: BEQ</option>
<option value="19910">Aerolineas Latinas: LNQ</option>
<option value="19911">Air Aruba: FQ</option>
<option value="19912">Cayman Airways Limited: KX</option>
<option value="19913">Belize Trans Air: 4H</option>
<option value="19914">Air Liberte: LRQ</option>
<option value="19915">Sea Air Shuttle: SAH</option>
<option value="19916">Primeras Lineas Uruguays For International: PU</option>
<option value="19917">United Parcel Service: 5X</option>
<option value="19918">Gulf Air Taxi: GAT</option>
<option value="19919">Adirondack Airlines: ADR</option>
<option value="19920">Corporate Air: CRP</option>
<option value="19921">Drummond Island Air: DIA</option>
<option value="19922">Gulf Flite Center: GFC</option>
<option value="19923">Lapsa: LAP</option>
<option value="19924">L'Express: LEX</option>
<option value="19925">Travelair: TVL</option>
<option value="19926">Valley Air Services: VAS</option>
<option value="19927">Aerosur (1): ASQ</option>
<option value="19928">Central American Airlines: GW (1)</option>
<option value="19929">Charter One: CHT</option>
<option value="19930">Alaska Airlines Inc.: AS</option>
<option value="19931">Regal Air: 2R</option>
<option value="19932">Apa International Air S.A.: 7P</option>
<option value="19933">Air New Zealand: NZ</option>
<option value="19934">Das Air Cargo: SE (1)</option>
<option value="19935">Star Aviation: SRA</option>
<option value="19936">Territorial Airlines: TRR</option>
<option value="19937">Loken Aviation: LKN</option>
<option value="19938">Dawn Air: DWN</option>
<option value="19939">Flying Boat: FYB</option>
<option value="19940">Caraven S.A.: CVQ</option>
<option value="19941">Trans Europ. Airways France: EFQ</option>
<option value="19942">General Air Cargo: GCQ</option>
<option value="19943">Allied Airlines: ALD</option>
<option value="19944">Airvantage: AVG</option>
<option value="19945">Chicago Air Taxi: CGO</option>
<option value="19946">Great Western Aviation: GWA</option>
<option value="19947">Paradise Island Airlines: PRD</option>
<option value="19948">Redwing Airways: RDW</option>
<option value="19949">Lauda Air Luftfahrt Ag: NG</option>
<option value="19950">Flagship Express Services: 9R</option>
<option value="19951">Braniff International Airlines Inc.: BE</option>
<option value="19952">Carnival Air Lines Inc.: KW</option>
<option value="19953">Transportes Aereos Mercantiles Panamericanos S.A: QT</option>
<option value="19954">Japan Air Charter Co. Ltd.: JZ</option>
<option value="19955">Affretair: ZL</option>
<option value="19956">Servicios Avensa: VC</option>
<option value="19957">Mcclain Airlines Inc.: MU (1)</option>
<option value="19958">China Eastern Airlines: MU</option>
<option value="19959">Dulles Express: DUL</option>
<option value="19960">Skybus Express Airlines: SYB</option>
<option value="19961">Air Transat: TS</option>
<option value="19962">Hawaii Pacific Air: XAH</option>
<option value="19963">World Air Network: WL (1)</option>
<option value="19964">Island Express: IPS</option>
<option value="19965">Rocky Mountain Helicopters: RMH</option>
<option value="19966">Sierra Nevada Airways: SNV</option>
<option value="19967">Trans World Express: TWE</option>
<option value="19968">Arizona Pacific Airways: AZP</option>
<option value="19969">International Cargo Xpress: XPQ</option>
<option value="19970">Northeast Express Regional (1): NER</option>
<option value="19971">Northeast Express Regional: NEX</option>
<option value="19972">Av Atlantic: HCQ</option>
<option value="19973">Aerotour Dominicano Cxa: RTQ</option>
<option value="19974">Aero Uruguay (1): ROQ</option>
<option value="19975">Aero Uruguay: URQ</option>
<option value="19976">Air North: 4N</option>
<option value="19977">United Air Lines Inc.: UA</option>
<option value="19978">Air Alpha: AHA</option>
<option value="19979">Alliance Air: AIY</option>
<option value="19980">Florida Air: FLA</option>
<option value="19981">Patriot Airlines Inc.: PAQ</option>
<option value="19982">USAir Shuttle: TB (1)</option>
<option value="19983">Key Airlines Inc.: ZN</option>
<option value="19984">Translift Airways Limited: FB</option>
<option value="19985">Turks Air Ltd.: KTQ</option>
<option value="19986">Turks Air Ltd. (1): BHQ</option>
<option value="19987">Advantage Airlines: ADV</option>
<option value="19988">Air West Airlines: AWA</option>
<option value="19989">Keene Airways: KEA</option>
<option value="19990">Sky One Express: SOE</option>
<option value="19991">America West Airlines Inc.: HP (Merged with US Airways 9/05.Stopped reporting 10/07.)</option>
<option value="19992">Hispaniola Airways: ZS</option>
<option value="19993">Airmark Airlines Inc.: AKQ</option>
<option value="19994">Reno Air Inc.: QQ</option>
<option value="19995">Aces Airlines: VX (1)</option>
<option value="19996">Nicaraguense De Aviacion Sa: 6Y</option>
<option value="19997">Jet America Airlines Inc.: SI (1)</option>
<option value="19998">Sierra Pacific Airlines: SI</option>
<option value="19999">South Pacific Island Airway: SOP</option>
<option value="20000">Time Air Sweden Ab: HK</option>
<option value="20001">Tranps Aereos Guatemaltecos: TGQ</option>
<option value="20002">Morris Air Corporation: KN</option>
<option value="20003">Balkan Bulgarian Airlines: LZ</option>
<option value="20004">Cal Air International Ltd.: BR (1)</option>
<option value="20005">Eva Airways Corporation: BR</option>
<option value="20006">Capitol Air Express Inc.: CPQ</option>
<option value="20007">Atlas Air Inc.: 5Y</option>
<option value="20008">Ram Aviation: RMV</option>
<option value="20009">Eclipse Airlines: ECL</option>
<option value="20010">Aero Transcolombiana: CLQ</option>
<option value="20011">Air Casino: ASN</option>
<option value="20012">Express Airlines II: EXP</option>
<option value="20013">Rader Aviation: RDR</option>
<option value="20014">Trans American Charter: ECQ</option>
<option value="20015">Export Air Del Peru S.A.: EXQ</option>
<option value="20016">Lineas Aereas Allegro: LGQ</option>
<option value="20017">Continental Micronesia: CS</option>
<option value="20018">J.D.Valenciana De Aviation: V5</option>
<option value="20019">Private Jet Expeditions: 5J (1)</option>
<option value="20020">Eagle Airlines: V9</option>
<option value="20021">Eagle Airlines (1): ECA</option>
<option value="20022">Leisure International Airways Ltd.: LZQ</option>
<option value="20023">Malev Hungarian Airlines: MA</option>
<option value="20024">Serv. Aerolineas Mexicanas: SMQ</option>
<option value="20025">Lineas Aereas Suramerican: LSQ</option>
<option value="20026">Quassar De Mexico: OMQ</option>
<option value="20027">Oasis International Airlines S.A.: OB</option>
<option value="20028">Aerochago S.A.: G3 (1)</option>
<option value="20029">Transp. Aereos Ejecutivos: GD</option>
<option value="20030">Aerolineas Uruguayas S.A.: UYQ</option>
<option value="20031">People Express Airlines Inc.: PE (1)</option>
<option value="20032">Air Europe S.P.A.: PE</option>
<option value="20033">UFS Inc.: U2</option>
<option value="20034">Pacific International Airlines: PIQ</option>
<option value="20035">Air Florida Express: AFE</option>
<option value="20036">American Flight Group: AFG</option>
<option value="20037">Aviation Sales: AVL</option>
<option value="20038">Business Helicopters: BUH</option>
<option value="20039">Four Star Aviation: FRS</option>
<option value="20040">Sky-Jet: SKJ</option>
<option value="20041">Salair: SLR</option>
<option value="20042">Southern Air Transport Inc.: SAQ</option>
<option value="20043">Air Ukraine: 6U</option>
<option value="20044">Aeromonterrey S.A.: 7M</option>
<option value="20045">Biman Bangladesh Airlines: BG</option>
<option value="20046">Air Wisconsin Airlines Corp: ZW</option>
<option value="20047">Caribair: CRB</option>
<option value="20048">Gorda Aero Service: GRA</option>
<option value="20049">Western Air Lines Inc.: WA (1)</option>
<option value="20050">Worldwide Airlines Services: WA</option>
<option value="20051">USAfrica Airways Inc.: E8</option>
<option value="20052">Skyjet S.A.: SBQ</option>
<option value="20053">Servicio Aereo Leo Lopez: 8L</option>
<option value="20054">Gulf Air Transport Inc.: GF (1)</option>
<option value="20055">Gulf Air Company: GF</option>
<option value="20056">Antigua Paradise Airways: PDQ</option>
<option value="20057">Evergreen International Inc.: EZ</option>
<option value="20058">Air Pacific Ltd. (1): FJ (1)</option>
<option value="20059">Air Pacific Ltd.: FJ</option>
<option value="20060">Air South Inc. (1): WV (1)</option>
<option value="20061">Air South Inc.: ASC</option>
<option value="20062">Island Air Charters: ICH</option>
<option value="20063">Pacificair: PFA</option>
<option value="20064">Ghana Airways Corporation: GH</option>
<option value="20065">Sky Service F.B.O.: SEQ</option>
<option value="20066">Advance Air Charters: AAQ</option>
<option value="20067">Mahalo Air: MHO</option>
<option value="20068">Capitol Air: CPT</option>
<option value="20069">Dolphin Express: DXA</option>
<option value="20070">Grand Airways Inc.: QD</option>
<option value="20071">Jetall Airways: 8J</option>
<option value="20072">Scanair: SIQ (1)</option>
<option value="20073">Premiair: SIQ</option>
<option value="20074">Renown Aviation: REQ</option>
<option value="20075">Aeromar C. Por A.: BQ</option>
<option value="20076">Texas Airways: TXY</option>
<option value="20077">Halisa Air: WD</option>
<option value="20078">Western Pacific Airlines: W7</option>
<option value="20079">Brasair Transportes Aereos: BTQ</option>
<option value="20080">Uzbekistan Airways: HY</option>
<option value="20081">Downeast Flying Service: DFS</option>
<option value="20082">Pine State Airlines: PNS</option>
<option value="20083">Sunshine Airlines: SUA</option>
<option value="20084">Aspen Airways Inc.: APN</option>
<option value="20085">Aeromexpress: QO</option>
<option value="20086">Tristar Airlines Inc.: T3</option>
<option value="20087">Sierra Expressway: SXP</option>
<option value="20088">Tower Air Inc.: FF</option>
<option value="20089">Serv De Trans Aereos Fuegui: FS</option>
<option value="20090">Royal Air: QN</option>
<option value="20091">Krasair: 7B</option>
<option value="20092">Merlin Express: MLX</option>
<option value="20093">Custom Air Transport: CTQ</option>
<option value="20094">Jettrain Airlines: LF (1)</option>
<option value="20095">World Airways Inc.: WO</option>
<option value="20096">Mexicargo: GJ (1)</option>
<option value="20097">Prestige Airways: OI</option>
<option value="20098">Eagle Jet Charter: EGJ</option>
<option value="20099">Laker Airways Inc.: 6F</option>
<option value="20100">Polar Air Cargo Airways: PO</option>
<option value="20101">Southern Frontier Air Trans: SFQ (1)</option>
<option value="20102">Pacific International Airlines Inc.: SFQ</option>
<option value="20103">North East Cargo Airlines: NEQ</option>
<option value="20104">Transaero Airlines: UN</option>
<option value="20105">Ecuatoriana De Aviacion: EU</option>
<option value="20106">Sunworld International Airlines: SM</option>
<option value="20107">Federal Express Corporation: FX</option>
<option value="20108">Northern Air Cargo Inc.: NC</option>
<option value="20109">Blue Scandinavia Ab: TRQ</option>
<option value="20110">Antonov Company: ADB</option>
<option value="20111">DHL Aero Expresso: DHQ</option>
<option value="20112">Maverick Airways: MAV</option>
<option value="20113">Golden West Airlines Inc.: GDW</option>
<option value="20114">Air Caribbean (1): XC</option>
<option value="20115">Air Caribbean: AIC</option>
<option value="20116">Canada 3000 Airlines Ltd.: 2T</option>
<option value="20117">Sobelair: Q7 (1)</option>
<option value="20118">Air Illinois Inc.: UX (1)</option>
<option value="20119">Air Europa: UX</option>
<option value="20120">Condor Flugdienst: DE</option>
<option value="20121">Air Atlantic Dominicana: LU</option>
<option value="20122">Mountain Air Express: MTX</option>
<option value="20123">Aeroejecutivo S.A.: SX (1)</option>
<option value="20124">City Bird: H2</option>
<option value="20125">Panagra Airways: PNQ</option>
<option value="20126">Laker Airways: GKQ</option>
<option value="20127">Lb Limited: 7Z</option>
<option value="20128">Flying Colours Airlines Ltd.: MT (1)</option>
<option value="20129">Sky Trek International Airlines: 1I</option>
<option value="20130">M & N Aviation: MNA</option>
<option value="20131">Jim Air Inc.: JMA</option>
<option value="20132">Cascade Airways Inc.: CZ (1)</option>
<option value="20133">China Southern Airlines: CZ</option>
<option value="20134">Jamaica Air Freighters: JAQ</option>
<option value="20135">Nacnet: NET</option>
<option value="20136">Magadan Airlines: H5</option>
<option value="20137">Sunworld International Airways Inc.: JK (1)</option>
<option value="20138">Spanair S.A.: JK</option>
<option value="20139">Air Atlanta Inc.: CC (1)</option>
<option value="20140">Air Atlanta Icelandic: CC</option>
<option value="20141">Austin Express Inc.: AUX</option>
<option value="20142">Flagship Airlines Inc.: 8N</option>
<option value="20143">Kiwi International: KP</option>
<option value="20144">Transportes Aereos Nacional: TX (1)</option>
<option value="20145">Soc.Nouvelle Air Guadeloupe: TX</option>
<option value="20146">Sun Pacific International: SPQ</option>
<option value="20147">TransMeridian Airlines: T9</option>
<option value="20148">Martinair Holland N.V.: MP</option>
<option value="20149">Florida West Airlines Inc.: PRQ</option>
<option value="20150">Harlequin Air Corporation: HQQ</option>
<option value="20151">Amerijet International: M6</option>
<option value="20152">Aviacsa Airlines: 6A</option>
<option value="20153">Ethiopian Airlines: ET</option>
<option value="20154">Airbus Transport Internat'l: BGQ</option>
<option value="20155">Aeropostal Alas De Venezuel: VH</option>
<option value="20156">ABSA-Aerolinhas Brasileiras: M3</option>
<option value="20157">Swiss World Airways: SO</option>
<option value="20158">Av Center Inc.: AVC</option>
<option value="20159">Express Air d/b/a Sunrise: XPA</option>
<option value="20160">Braniff Inc.: BN (1)</option>
<option value="20161">Britannia Airways GmbH: BN</option>
<option value="20162">Air Tahiti Nui: TN</option>
<option value="20163">Translux Intl Airlines: LXQ</option>
<option value="20164">Accessair Holdings: ZA</option>
<option value="20165">Queen Air: 5G (1)</option>
<option value="20166">Gulf And Caribbean Cargo: GFQ</option>
<option value="20167">Transportes Aeros Meridiona: JJ</option>
<option value="20168">Eastwind Airlines Inc.: W9</option>
<option value="20169">Lynden Air Cargo Airlines: L2</option>
<option value="20170">Mesaba Airlines: XJ</option>
<option value="20171">American International Airways Inc.: NI (1)</option>
<option value="20172">Lanica: NI</option>
<option value="20173">Kitty Hawk International: CDQ</option>
<option value="20174">Air Ketchum Idaho Inc.: AIK</option>
<option value="20175">Luxair: LG</option>
<option value="20176">National Airlines: N7</option>
<option value="20177">Asia Pacific: PFQ</option>
<option value="20178">Lorair Ltd.: LOQ</option>
<option value="20179">TUIfly Nordic A.B.: 6B</option>
<option value="20181">Trans International Express: TIE</option>
<option value="20182">Lapa-Lineas Aereas Privadas: MJ</option>
<option value="20183">Czech Airlines: OK</option>
<option value="20184">Novair Airlines Ab: NOQ</option>
<option value="20185">Jalways Co. Ltd.: JO</option>
<option value="20186">Sterling Cargo: NB</option>
<option value="20187">The Hawaii Express Inc.: LP (1)</option>
<option value="20188">Lan Peru Airlines: LP</option>
<option value="20189">Aero Continente: N6</option>
<option value="20190">Southern Air Inc.: 9S</option>
<option value="20191">Fine Airlines Inc.: FNQ</option>
<option value="20192">Vanguard Airlines Inc.: NJ</option>
<option value="20193">Gemini Air Cargo Airways: GR</option>
<option value="20194">Arrow Air Inc.: JW</option>
<option value="20195">Sky Lease Cargo: WI</option>
<option value="20196">Air Malta: KM</option>
<option value="20197">Casino Airlines (1): CSN</option>
<option value="20198">Casino Airlines: CSA</option>
<option value="20199">Farwest Airlines: FRW</option>
<option value="20200">C.A.L Cargo Airlines: 5C</option>
<option value="20201">Ameristar Air Cargo: AMQ</option>
<option value="20202">Chicago Express Airlines: C8 (1)</option>
<option value="20203">Falcon Air Express: FCQ</option>
<option value="20204">Champion Air: MG</option>
<option value="20205">Aeromaritime: OV</option>
<option value="20206">Jazz Aviation LP: QK</option>
<option value="20207">XTRA Airways: XP</option>
<option value="20208">Taca Peru: TQQ</option>
<option value="20209">Air Japan Co: NQ</option>
<option value="20210">Privatair: PBQ</option>
<option value="20211">Trans World Airways LLC: TW</option>
<option value="20212">Sunair Express LLC: SUX</option>
<option value="20213">Polyot Airlines: POQ</option>
<option value="20214">Avia Leasing Company: AD (1)</option>
<option value="20215">Best Airlines Inc.: IW (1)</option>
<option value="20216">Air Liberte Aka Aom Minerve: IW</option>
<option value="20217">Air Excursions LLC (1): AEX</option>
<option value="20218">Express One International Inc.: JKQ</option>
<option value="20219">Village Aviation: VLA</option>
<option value="20220">Air 21: A7 (1)</option>
<option value="20221">Air Comet S.A.: A7</option>
<option value="20222">Estafeta Carga Aereas: E7</option>
<option value="20223">F.S. Air Service: FSA</option>
<option value="20224">Katmai Air: KAT</option>
<option value="20225">Peninsula Airways Inc.: KS</option>
<option value="20226">Spernak Airways Inc.: SNK</option>
<option value="20227">Vensecar International: V4</option>
<option value="20228">Suncoast Airlines Inc.: WS (1)</option>
<option value="20229">Westjet: WS</option>
<option value="20230">Lineas Aereas Azteca: ZE (1)</option>
<option value="20231">Dutch Caribbean Airlines: K8</option>
<option value="20232">Cielos De Peru: A2</option>
<option value="20233">Swiss International Airlines: LX</option>
<option value="20234">Edelweiss Air Ag: 8R</option>
<option value="20235">Conner Air Lines Inc.: 4S (1)</option>
<option value="20236">Sol Air (Aero Hunduras): 4S</option>
<option value="20237">Trans States Airlines: AX</option>
<option value="20238">Southern Wind Airlines: A4</option>
<option value="20239">All Canada Express: CEQ</option>
<option value="20240">Ccair: SNB</option>
<option value="20241">Sunrise Airlines Inc.: ASW</option>
<option value="20242">North Vancouver Air: NXQ</option>
<option value="20243">Valujet Airlines Inc.: J7</option>
<option value="20244">Potomac Air: POA</option>
<option value="20245">Great Plains Airlines Inc.: TRI</option>
<option value="20246">Atlantic Coast Jet Inc.: ACJ</option>
<option value="20247">Rio Grande Air: EWA</option>
<option value="20248">Wilburs Inc.: 8F</option>
<option value="20249">Nevis Express: NVX</option>
<option value="20250">Aerolitoral: 5D</option>
<option value="20251">Westair Airlines Inc.: OE</option>
<option value="20252">Pacific Island Aviation: 9J</option>
<option value="20253">Cape Air: 9K</option>
<option value="20254">Colgan Air: 9L</option>
<option value="20255">Central Mountain Air: 9M</option>
<option value="20256">Arizona Airways: ARZ</option>
<option value="20257">Bemidji Airlines: CH</option>
<option value="20258">Big Sky Airlines Inc.: GQ</option>
<option value="20259">European Aviation Air Charter: E72</option>
<option value="20260">Worldwide Airlines Inc.: WLQ</option>
<option value="20261">Ellis Air Taxi Inc.: ELL</option>
<option value="20262">Empire Airlines Inc. (1): UR</option>
<option value="20263">Empire Airlines Inc.: EM</option>
<option value="20264">Empire Airlines Inc. (2): EMP</option>
<option value="20265">Freedom Airlines d/b/a HP Expr: F8</option>
<option value="20266">G5 Executive Ag: GBQ</option>
<option value="20267">Grand Canyon Helicopters: GCH</option>
<option value="20268">Global Supply System: GSQ</option>
<option value="20269">Allegheny Airlines: HRZ</option>
<option value="20270">Helijet International Inc.: JB</option>
<option value="20271">Winair Inc.: WNQ</option>
<option value="20272">Kenmore Air Harbor: KAH</option>
<option value="20273">New England Airlines Inc.: NEW</option>
<option value="20274">Northwest Seaplanes: NWS</option>
<option value="20275">Ozark Air Lines Inc. (1): OZ (1)</option>
<option value="20276">Ozark Air Lines Inc.: OZA</option>
<option value="20277">Asiana Airlines Inc.: OZ</option>
<option value="20278">Mytravel Airways: RNQ</option>
<option value="20279">Air-Serve: RSV</option>
<option value="20280">Seaborne Aviation: SEB</option>
<option value="20281">Mountain Bird/Salmon Air: S6 (1)</option>
<option value="20282">Samoa Aviation Inc.: SMO</option>
<option value="20283">Trans Continental Airlines: YB</option>
<option value="20284">Express.Net Airlines: TCQ</option>
<option value="20285">Ward Air: WRD</option>
<option value="20286">Vintage Props & Jets Inc.: VQ</option>
<option value="20287">Island Air Hawaii: WP</option>
<option value="20288">Trans International Airlines Inc.: TFQ</option>
<option value="20289">Friday Harbor Seaplanes: WST</option>
<option value="20290">Air St. Thomas: ZP</option>
<option value="20291">Air Midwest Inc.: ZV</option>
<option value="20292">Airbc Ltd.: ZX (1)</option>
<option value="20293">Air Georgian: ZX</option>
<option value="20294">Jetsgo: SG</option>
<option value="20295">Midway Airlines Inc. (1): ML (1)</option>
<option value="20296">Aero Costa Rica: ML</option>
<option value="20297">Midway Airlines Inc.: JI (1)</option>
<option value="20298">Jes Air Ltd.: JX (1)</option>
<option value="20299">Southeast Airlines: JX</option>
<option value="20300">Pacific Wings Airlines: LW</option>
<option value="20301">Kar-Air Oy: KR (1)</option>
<option value="20302">Kitty Hawk Aircargo: KR</option>
<option value="20303">Nolinor Aviation: NLQ</option>
<option value="20304">SkyWest Airlines Inc.: OO</option>
<option value="20305">Pace Airlines: PCQ</option>
<option value="20306">Challenge Air Transport Inc.: VV (1)</option>
<option value="20307">Challenge Air International Inc.: VV (2)</option>
<option value="20308">Centurion Cargo Inc.: WE</option>
<option value="20309">Aerosvit Ukranian Airlines: VV</option>
<option value="20310">Caribbean Sun Airlines, Inc. d/b/a World Atlantic Airlines: WL</option>
<option value="20311">Jet Connection Businessflight Ag: JCQ</option>
<option value="20312">ATA Airlines d/b/a ATA: TZ</option>
<option value="20313">Cargojet Airways Ltd.: W8</option>
<option value="20314">Midwest Airline, Inc.: YX (1)</option>
<option value="20315">Bellair Inc. (1): 7G (1)</option>
<option value="20316">Bellair Inc.: 5B</option>
<option value="20317">MK Airlines Ltd.: 7G</option>
<option value="20318">Olson Air Service: 4B (1)</option>
<option value="20319">Smokey Bay Air Inc.: 2E</option>
<option value="20320">Frontier Flying Service: 2F</option>
<option value="20321">British Airtours Limited: 4E</option>
<option value="20322">Tanana Air Service: 4EQ</option>
<option value="20323">Warbelow: 4W</option>
<option value="20324">Yute Air Aka Flight Alaska: 4Y</option>
<option value="20325">Arctic Circle Air Service: 5F</option>
<option value="20326">Cape Smythe Air Service: 6C</option>
<option value="20327">Era Aviation: 7H</option>
<option value="20328">Inland Aviation Services: 7N</option>
<option value="20329">Skystar International Inc.: 7S (1)</option>
<option value="20330">Arctic Transportation: 7S</option>
<option value="20331">Bering Air Inc.: 8E</option>
<option value="20332">Baker Aviation Inc.: 8Q</option>
<option value="20333">Wright Air Service: 8V</option>
<option value="20334">Thomas Cook Airlines Uk Ltd.: MT</option>
<option value="20335">Boston-Maine Airways: E9</option>
<option value="20336">Hageland Aviation Service: H6</option>
<option value="20337">Kalinin Aviation LLC d/b/a Alaska Seaplanes: J5</option>
<option value="20338">Larrys Flying Service: J6</option>
<option value="20339">L.A.B. Flying Service Inc.: JF</option>
<option value="20340">Seaport Airlines, Inc.: K5</option>
<option value="20341">Alaska Central Express: KO</option>
<option value="20342">40-Mile Air: Q5</option>
<option value="20343">Airlift International Inc.: RD (1)</option>
<option value="20344">Ryan International Airlines: RD</option>
<option value="20345">Regency Air: RGQ</option>
<option value="20346">Iliamna Air Taxi: V8</option>
<option value="20347">Pro Air Inc.: P9</option>
<option value="20348">Lan Ecuador: XL</option>
<option value="20349">Promech: Z3 (1)</option>
<option value="20350">Lan Dominica: 4M (1)</option>
<option value="20351">Primaris Airlines Inc.: FE</option>
<option value="20352">Westward Airways Inc.: WAW</option>
<option value="20353">Dynamic Aviation, Inc. d/b/a Beacon: 8D</option>
<option value="20354">Aerodynamics Inc. d/b/a SkyValue d/b/a SkyValue Airways: AJQ</option>
<option value="20355">US Airways Inc.: US (Merged with America West 9/05. Reporting for both starting 10/07.)</option>
<option value="20356">Skyway Airlines: AL</option>
<option value="20357">Astar USA, LLC: ER</option>
<option value="20358">Great Lakes Airlines: ZK</option>
<option value="20359">Triair Bermuda Flt Operations: TBQ</option>
<option value="20360">Sata Internacional: S4</option>
<option value="20361">Valley Air Express Inc.: 2U</option>
<option value="20362">China Cargo Airline: CK</option>
<option value="20363">Endeavor Air Inc.: 9E</option>
<option value="20364">Canjet Airlines: C6</option>
<option value="20365">Aviation Concepts: CZQ</option>
<option value="20366">ExpressJet Airlines Inc.: EV</option>
<option value="20367">Freedom Air: FRA</option>
<option value="20368">Allegiant Air: G4</option>
<option value="20370">Kalitta Air LLC: KAQ</option>
<option value="20371">Reliant Airlines: RLQ</option>
<option value="20372">Kalitta Charters II: KLQ</option>
<option value="20373">Propair: PPQ</option>
<option value="20374">ExpressJet Airlines Inc. (1): XE</option>
<option value="20375">First Choice Airways: TZQ</option>
<option value="20376">Mn Aviation, Inc.: W4</option>
<option value="20377">Omni Air International LLC: X9</option>
<option value="20378">Mesa Airlines Inc.: YV</option>
<option value="20379">Zantop International: ZKQ</option>
<option value="20380">SkyLink Express Inc.: PEQ</option>
<option value="20381">Air Atlanta Europe: EUQ</option>
<option value="20382">Victory Air Transport Inc.: VCQ</option>
<option value="20383">Venture Travel LLC d/b/a Taquan Air Service: K3</option>
<option value="20384">Pan American World Airways (1): PA (1)</option>
<option value="20385">Air Panama Internacional: OP (1)</option>
<option value="20386">Pan American World Airways: PA (2)</option>
<option value="20387">Pan American Airways Corp.: PN</option>
<option value="20388">Flying Boat Inc.: OP</option>
<option value="20389">Florida Coastal Airlines: PA</option>
<option value="20390">Belair Airlines Ltd.: 4T</option>
<option value="20391">Israir Airlines: 6H</option>
<option value="20392">Emirates: EK</option>
<option value="20393">Business Express: HQ (1)</option>
<option value="20394">Harmony Airways: HQ</option>
<option value="20395">Sociedad Aeronautica De Med: MM (1)</option>
<option value="20396">Euro Atlantic Airways: MM</option>
<option value="20397">PSA Airlines Inc.: OH</option>
<option value="20398">Envoy Air: MQ</option>
<option value="20399">Planet Airways: PLQ</option>
<option value="20400">Capital Cargo International: PT (1)</option>
<option value="20401">Silver Airways: 3M</option>
<option value="20402">Miami Air International: GL</option>
<option value="20403">Discovery Airways Inc.: DH (1)</option>
<option value="20404">Independence Air: DH</option>
<option value="20405">National Air Cargo Group Inc d/ba National Airlines: N8</option>
<option value="20406">NetJets Large Aircraft Company L.L.C.: BNQ</option>
<option value="20407">Regions Air, Inc.: 3C</option>
<option value="20408">Tatonduk Outfitters Limited d/b/a Everts Air Alaska and Everts Air Cargo: 5V</option>
<option value="20409">JetBlue Airways: B6</option>
<option value="20410">Celtic Tech Jet Ltd.: CSQ</option>
<option value="20411">Arizona Express: K7</option>
<option value="20412">Nations Air Express Inc.: N5 (1)</option>
<option value="20413">Skagway Air Service: N5</option>
<option value="20414">Executive Airlines: OW</option>
<option value="20415">North American Airlines: NA</option>
<option value="20416">Spirit Air Lines: NK</option>
<option value="20417">Comair Inc.: OH (1)</option>
<option value="20418">Chautauqua Airlines Inc.: RP</option>
<option value="20419">Aerolineas Nicaraguenses: RL (1)</option>
<option value="20420">UltrAir: RL</option>
<option value="20421">Sky King Inc.: SLQ</option>
<option value="20422">Sun Country Airlines d/b/a MN Airlines: SY</option>
<option value="20423">USA 3000 Airlines: U5</option>
<option value="20424">Grand Canyon Airlines, Inc. d/b/a Grand Canyon Airlines d/b/a Scenic Airlines: YR</option>
<option value="20425">Viscount Air Service Inc.: VIQ (1)</option>
<option value="20426">Vieques Air Link Inc.: VI</option>
<option value="20427">Piedmont Airlines: PT</option>
<option value="20428">Volga-Dnepr Airlines: VIQ</option>
<option value="20429">Aero Laguna S.A. De C.V.: AVQ</option>
<option value="20430">Aerodan S.A. De C.V.: AYQ</option>
<option value="20431">Aero Rentas De Coahuila S.A. De C.V.: BAQ</option>
<option value="20432">Aerotaxis De Aguascalientes S.A. De C.V.: BDQ</option>
<option value="20433">Servicios Aeronauticos Z S.A. De C.V.: BIQ</option>
<option value="20434">Taxirey S.A. De C.V.: BJQ</option>
<option value="20435">Frontier Airlines Inc. (1): FL (1)</option>
<option value="20436">Frontier Airlines Inc.: F9</option>
<option value="20437">AirTran Airways Corporation: FL</option>
<option value="20438">Air Club International: HB (1)</option>
<option value="20439">Homer Air: HB</option>
<option value="20440">Lineas Aereas Del Caribe: LC (1)</option>
<option value="20441">Legend Airlines: LC (2)</option>
<option value="20442">Varig Logistica S/A: LC</option>
<option value="20443">Island Air Service: 2O</option>
<option value="20444">Excel Airways: JN</option>
<option value="20445">Commutair Aka Champlain Enterprises, Inc.: C5</option>
<option value="20446">Aerotransportes Mas De Crga: M7</option>
<option value="20447">USA Jet Airlines Inc.: U7</option>
<option value="20448">Shuttle America Corp.: S5</option>
<option value="20449">Aero-Services-Corporate: WEQ</option>
<option value="20450">Omega Air Holdings d/b/a Focus Air: F2</option>
<option value="20451">Transmile Air Service: TH</option>
<option value="20452">Republic Airlines: YX</option>
<option value="20453">ABX Air Inc: ABX</option>
<option value="20454">EOS Airlines, Inc.: E0</option>
<option value="20455">Grant Aviation: GV</option>
<option value="20456">Air Foyle Limited: GS</option>
<option value="20500">GoJet Airlines LLC d/b/a United Express: G7</option>
<option value="20501">Morningstar Air Express: MOQ</option>
<option value="20502">MAXjet: MY</option>
<option value="21007">Abaco Air, Ltd.: BZQ</option>
<option value="21008">Challenge Air Luftverkehrs GmbH: CAQ</option>
<option value="21022">PM Air, LLC: Z3</option>
<option value="21029">Harris Air Services: HBQ</option>
<option value="21035">Tyrolean Jet Service: TIQ</option>
<option value="21036">Executive Airlines, SL: EAQ</option>
<option value="21040">Titan Airways: 02Q</option>
<option value="21059">TUI Airlines Nederland B.V.: OR</option>
<option value="21061">Aerounion Aerotransporte de Carga Union SA de CV: 6R</option>
<option value="21069">Cargo 360, Inc.: GG</option>
<option value="21070">Globespan Airways Limited d/b/a Flyglobespan: Y2</option>
<option value="21074">Arrow Panama: WAP</option>
<option value="21080">Tradewind Aviation: 04Q</option>
<option value="21084">LAN Argentina: 4M</option>
<option value="21089">US Helicopter Corporation: UH</option>
<option value="21094">Comlux Aviation, AG: 05Q</option>
<option value="21099">NetJets Transportes Aereos, S.A.: NJE</option>
<option value="21107">Etihad Airways: EY</option>
<option value="21111">Pacific Airways, Inc.: 3F</option>
<option value="21116">Flyjet Limited d/b/a Silverjet: Y7</option>
<option value="21117">TravelspanGT, Inc. S.A.: 9T</option>
<option value="21118">Zeal 320: 37</option>
<option value="21121">Elysair d/b/a L'Avion: A0</option>
<option value="21126">ANA & JP Express Co. Ltd.: 9N</option>
<option value="21131">VistaJet Luftfahrtunternehmen GmbH: VSA</option>
<option value="21132">Master Top Linhas Aereas Ltd.: 06Q</option>
<option value="21134">JetClub AG: 0J</option>
<option value="21136">Flair Airlines Ltd.: 07Q</option>
<option value="21142">Avior Airlines, C.A.: 9V</option>
<option value="21147">Flying Service N.V.: 0Q</option>
<option value="21148">Master Top Linhas Aereas, Ltda.: Q4</option>
<option value="21158">Global Jet Austria, GmbH: IGA</option>
<option value="21160">Global Jet Luxembourg, Sa: SVW</option>
<option value="21161">Swift Air, LLC: 09Q</option>
<option value="21167">Compass Airlines: CP</option>
<option value="21171">Virgin America: VX</option>
<option value="21177">Skybus Airlines, Inc.: SX</option>
<option value="21181">Skyservice Airlines, Inc.: 5G</option>
<option value="21186">DCA: 0BQ</option>
<option value="21192">Eurofly S.p.A: GJ</option>
<option value="21196">ACM AIR CHARTER GmbH: 0CQ</option>
<option value="21201">Jade Cargo International: JI</option>
<option value="21202">CAT Aviation: CAZ</option>
<option value="21205">Inter Island Airways, d/b/a Inter Island Air: 0GQ</option>
<option value="21212">Polar Airlines de Mexico d/b/a Nova Air: 0HQ</option>
<option value="21217">Lynx Aviation d/b/a Frontier Airlines: L3</option>
<option value="21221">Vladivostok Air: XF</option>
<option value="21226">Porter Airlines, Inc.: PD</option>
<option value="21231">Sunwing Airlines Inc.: WG</option>
<option value="21236">Vision Airlines: 0JQ</option>
<option value="21242">Mokulele Flight Services, Inc.: MW</option>
<option value="21247">Star Air A/S: S6</option>
<option value="21248">Metropix UK, LLP.: 0LQ</option>
<option value="21253">Multi-Aero, Inc. d/b/a Air Choice One: 0MQ</option>
<option value="21258">Santa Barbara Airlines, C.A: S3</option>
<option value="21261">Jet Airways (India) Limited: 9W</option>
<option value="21262">Qatar Airways (Q.C.S.C): QR</option>
<option value="21266">Yangtze River Express Airlines Company: Y8</option>
<option value="21271">Hainan Airlines Company Limited: HU</option>
<option value="21281">JetAlliance Flugbetriebs d/b/a JAF Airservice: JAG</option>
<option value="21287">Open Skies: 0OQ</option>
<option value="21294">Aeromexico Travel: TRA</option>
<option value="21302">Pan American World Airways Dominicana: 7Q</option>
<option value="21306">TAG Aviation S.A.: FP</option>
<option value="21308">TAG Aviation (UK) Ltd.: 0QQ</option>
<option value="21309">TAG Aviation Espana S.L.: 0RQ</option>
<option value="21312">Air Greco, Inc., d/b/a Wings Air: WV</option>
<option value="21317">Corporatejets, XXI: 0TQ</option>
<option value="21323">Aerosur: 5L</option>
<option value="21326">Great Wall Airlines Company Limited: IJ</option>
<option value="21331">Comlux Malta, Ltd.: 0UQ</option>
<option value="21342">Aeroenlaces Nacionales, S.A. de C.V. d/b/a VivaAerobus: VB</option>
<option value="21346">Ocean Sky (UK) Limited: 0VQ</option>
<option value="21351">Concesionaria Vuela Compania De Aviacion SA de CV (Volaris): Y4</option>
<option value="21352">Avjet Corporation: 0WQ</option>
<option value="21356">Jetstar Airways Pty Limited: JQ</option>
<option value="21361">Air Berlin PLC and CO: AB</option>
<option value="21366">XL Airways France: SE</option>
<option value="21373">Aeroservices Executive: BES</option>
<option value="21376">Lan Colombia: L7</option>
<option value="21382">Comlux Malta Ltd.: 0YQ</option>
<option value="21386">Air Excursions LLC: X4</option>
<option value="21395">Virgin Blue International Airlines t/a V Australia: VA</option>
<option value="21402">Prescott Support Company, Inc.: PM</option>
<option value="21406">Acropolis Aviation Ltd.: CRV</option>
<option value="21407">Swiss Air Ambulance: 10Q</option>
<option value="21411">Insel Air International B V: 7I</option>
<option value="21416">Jin Air Co Ltd.: LJ</option>
<option value="21421">Jet Aviation Business Jets AG: PP</option>
<option value="21423">Unijet: 12Q</option>
<option value="21427">AeroLogic GmbH: 3S</option>
<option value="21433">Meridiana S.p.A: IG</option>
<option value="21434">Corsair International: SS</option>
<option value="21437">Chartright Air Inc.: 13Q</option>
<option value="21438">Hapag-Lloyd Executive GmbH: EXC</option>
<option value="21439">London Air Services Limited: 14Q</option>
<option value="21440">Air Alsie A/S: 15Q</option>
<option value="21447">Albinati Aeronautics SA: 17Q</option>
<option value="21452">Skymark Airlines Inc.: BC</option>
<option value="21463">Aerovias de Intergracian Regional: 4C</option>
<option value="21467">Arik Air International: W3</option>
<option value="21477">Via Airlines d/b/a Charter Air Transport: 1AQ</option>
<option value="21487">AirBridgeCargo Airlines Limited: RU</option>
<option value="21492">Dynamic Airways, LLC: 1BQ</option>
<option value="21503">Island Airlines LLC: 1DQ</option>
<option value="21507">Aerolineas Galapagos S A Aerogal: 2K</option>
<option value="21512">Travel Service, a.s.: QS</option>
<option value="21518">KaiserAir, Inc.: 1EQ</option>
<option value="21522">Alsek Air: 1FQ</option>
<option value="21528">Transportes Aeromar S.A de C.V: VW</option>
<option value="21532">Air Finland Ltd.: OF</option>
<option value="21548">International Jet Management GmbH: 1HQ</option>
<option value="21549">Jet link AG: 1IQ</option>
<option value="21552">TUI Airlines Belgium N.V. d/b/a Jetairfly: TB</option>
<option value="21557">Sichuan Airlines Co Ltd.: 3U</option>
<option value="21562">Exec Direct Aviation Services Limited: 1JQ</option>
<option value="21567">Brussels Airlines N.V.: SN</option>
<option value="21568">VistaJet Limited: VJT</option>
<option value="21569">Lauda Motion GmbH: LDM</option>
<option value="21570">Star Marianas Air Inc.: 1SQ</option>
<option value="21573">Bertelsmann Aviation GmbH: 1LQ</option>
<option value="21574">Air Company Yakutia: R3</option>
<option value="21577">Rhoades Aviation dba Transair: 1TQ</option>
<option value="21578">ABC Aerolineas SA de CV dba Interjet: 4O</option>
<option value="21579">Norwegian Air Shuttle ASA: DY</option>
<option value="21580">Cargolux Italia SpA: C8</option>
<option value="21582">Reeve Air Alaska, LLC: RVQ</option>
<option value="21587">Tame Linea Aerea del Ecuador Tme EP: EQ</option>
<option value="21589">Twin Cities Air Service LLC: 1MQ</option>
<option value="21590">Gainjet Aviation SA: 1UQ</option>
<option value="21592">Jeju Air Co Ltd.: 7C</option>
<option value="21594">Scott Air LLC dba Island Air Express: I4</option>
<option value="21596">Ultimate JetCharters LLC dba Ultimate Air Shuttle: 1WQ</option>
<option value="21597">JSC The 224th Flight Unit State Airlines: 1NQ</option>
<option value="21598">WOW Air ehf: WW</option>
<option value="21599">Boutique Air: 4B</option>
<option value="21601">Dassault Falcon Service: 1XQ</option>
<option value="21605">VRG Linhas Aereas S A: G3</option>
<option value="21607">Fly Jamaica Airways Limited: OJ</option>
<option value="21608">Ukraine International Airlines: PS</option>
<option value="21610">Air Canada rouge LP: RV</option>
<option value="21611">Sky Regional Airlines Inc.: RS</option>
<option value="21613">Makani Kai Air Charters: 1PQ</option>
<option value="21614">City Wings Inc dba Seaflight: 1QQ</option>
<option value="21615">Air Charter, Inc d/b/a Air Flamenco: 1YQ</option>
<option value="21618">Sun Air Express LLC dba Sun Air International: 1RQ</option>
<option value="21623">SkyBahamas Airlines Ltd.: Q7</option>
<option value="21624">Jet2.com: LS</option>
<option value="21626">Dreamjet SAS Dba La Compagnie: B0</option>
<option value="21629">Western Global: KD</option>
<option value="21630">Comlux Aruba NV: 1ZQ</option>
<option value="21631">Orange Air: 20Q</option>
<option value="21634">Aloha Air Cargo: KH</option>
<option value="21635">CFM Inc d/b/a Contour Airlines: LF</option>
<option value="21636">Gem Air LLC: 22Q</option>
<option value="21638">Azul Linhas Aereas Brazileiras S A: AD</option>
<option value="21645">Songbird Airways Inc.: 23Q</option>
<option value="21646">Blue Jet SP Z o o: 24Q</option>
<option value="21648">SkyGreece Airlines S A: GW</option>
<option value="21649">Mjet GmbH: 25Q</option>
<option value="21650">Eastern Airlines Group Inc.: EE</option>
<option value="21651">Albinati aviation Limited: 26Q</option>
<option value="21652">Jet Aviation Flight Services, Inc.: 27Q</option>
<option value="21653">Menagerie Enterprises Inc d/b/a Monarch Air: 28Q</option>
<option value="21655">Erickson Helicopters: 29Q</option>
<option value="21656">ABS JETS A.S: 2AQ</option>
<option value="21657">Air Asia X Berhad dba Airasia X: D7</option>
<option value="21659">Air Busan: BX</option>
<option value="21660">Air Medical Ltd.: 2BQ</option>
<option value="21667">Oceanair Linhas Aereas S A: O6</option>
<option value="21669">Aviation Partners of Boynton Beach LLC d/b/a Hummingbird Air: 2DQ</option>
<option value="21670">Fast Colombia SAS d/b/a Viva Colombia: FC</option>
<option value="21672">Inselair Aruba NV: 8I</option>
<option value="21673">J&M Alaska Air Tours, Inc. d/b/a Alaska Air Transit: 2EQ</option>
<option value="21674">Compagnie Aerienne Inter Regionale Express dba Air Antilles Express & Air Guyane: 3SD</option>
<option value="21677">Cebu Air Inc d/b/a Cebu Pacific Air: 5J</option>
<option value="21692">Azerbaijan Airlines CJSC: J2</option>
<option value="21693">Cavok Air LLC: 2GQ</option>
<option value="21694">Silk Way West Airlines: 7L</option>
<option value="21697">Orenburg Airlines: R2</option>
<option value="21702">WestJet Encore Ltd.: WR</option>
<option value="21707">Hong Kong Airlines Limited: HX</option>
<option value="21712">Elite Airways LLC: 2HQ</option>
<option value="21718">Delux Public Charter LLC: 2JQ</option>
<option value="21728">Eurowings GmbH: EW</option>
<option value="21733">Abelag Aviation AG: AAB</option>
<option value="21735">Longtail Aviation Ltd.: 2KQ</option>
<option value="21738">Air Serbia: JU</option>
<option value="21743">Tropic Ocean Airways LLC: 2LQ</option>
<option value="21745">LIMA NY Corp d/b/a Fly The Whale d/b/a Tailwind: 2NQ</option>
<option value="21749">Talofa Airways Limited: 2OQ</option>
<option value="21754">21 Air LLC: 2PQ</option>
<option value="21760">Luxaviation S A: 2RQ</option>
<option value="21764">Trans Northern Airways d/b/a Air Unlimited Charter Services: 2TQ</option>
<option value="21770">Xiamen Airlines Co., Ltd.: MF</option>
<option value="21774">Air Philippines Corp d/b/a Airphil Express, Philippines Airlines: 2P</option>
<option value="21780">Cargologicair Limited: P3</option>
<option value="21781">Eastar Jet Co Ltd.: ZE</option>
<option value="21785">Hong Kong Express Airways Limited: UO</option>
<option value="21809">Maine Aviation Aircraft Charter, LLC: 0FQ</option>
<option value="21814">Svenskt Industriflyg AB: 2UQ</option>
<option value="21820">Paklook Air, Inc d/b/a/ Airlift Alaska: K2</option>
<option value="21821">Beijing Capital Airlines: JD</option>
<option value="21823">Norwegian Air International Ltd.: D8</option>
<option value="21835">Public Charters, Inc. d/b/a North Country Sky d/b/a Regional Sky d/b/a Texas Sky: 30Q</option>
<option value="21854">Polaris Aviation Solutions, LLC: 34Q</option>
<option value="21860">Scoot Tigerair Pte Ltd d/b/a Scoot: TR</option>

