<option value="0">Not Applicable</option>
<option value="1">Alabama</option>
<option value="2">Alaska</option>
<option value="4">Arizona</option>
<option value="5">Arkansas</option>
<option value="6">California</option>
<option value="7">U.S. Minor Outlying Islands</option>
<option value="8">Colorado</option>
<option value="9">Connecticut</option>
<option value="10">Delaware</option>
<option value="11">District of Columbia</option>
<option value="12">Florida</option>
<option value="13">Georgia</option>
<option value="15">Hawaii</option>
<option value="16">Idaho</option>
<option value="17">Illinois</option>
<option value="18">Indiana</option>
<option value="19">Iowa</option>
<option value="20">Kansas</option>
<option value="21">Kentucky</option>
<option value="22">Louisiana</option>
<option value="23">Maine</option>
<option value="24">Maryland</option>
<option value="25">Massachusetts</option>
<option value="26">Michigan</option>
<option value="27">Minnesota</option>
<option value="28">Mississippi</option>
<option value="29">Missouri</option>
<option value="30">Montana</option>
<option value="31">Nebraska</option>
<option value="32">Nevada</option>
<option value="33">New Hampshire</option>
<option value="34">New Jersey</option>
<option value="35">New Mexico</option>
<option value="36">New York</option>
<option value="37">North Carolina</option>
<option value="38">North Dakota</option>
<option value="39">Ohio</option>
<option value="40">Oklahoma</option>
<option value="41">Oregon</option>
<option value="42">Pennsylvania</option>
<option value="44">Rhode Island</option>
<option value="45">South Carolina</option>
<option value="46">South Dakota</option>
<option value="47">Tennessee</option>
<option value="48">Texas</option>
<option value="49">Utah</option>
<option value="50">Vermont</option>
<option value="51">Virginia</option>
<option value="53">Washington</option>
<option value="54">West Virginia</option>
<option value="55">Wisconsin</option>
<option value="56">Wyoming</option>
<option value="60">American Samoa (Fips Pub 55-3)</option>
<option value="64">Federal States Of Micronesia (Fips Pub 55-3)</option>
<option value="66">Guam (Fips Pub 55-3)</option>
<option value="67">Johnston Atoll</option>
<option value="68">Marshall Islands (Fips Pub 55-3)</option>
<option value="69">Northern Mariana Islands (Fips Pub 55-3)</option>
<option value="70">Palau (Fips Pub 55-3)</option>
<option value="71">Midway Islands</option>
<option value="72">Puerto Rico (Fips Pub 55-3)</option>
<option value="74">U.S. Minor Outlying Islands</option>
<option value="75">Trust Territory Of Pacific Islands (Obsolete 1987)</option>
<option value="76">Navassa Island</option>
<option value="78">Virgin Islands (Fips Pub 55-3)</option>
<option value="79">Wake Island</option>
<option value="81">Baker Island</option>
<option value="84">Howland Island</option>
<option value="86">Jarvis Island</option>
<option value="89">Kingman Reef</option>
<option value="95">Palmyra Atoll</option>
<option value="96">U.S.Outlying Areas</option>
<option value="98">States With Population <2,000,000 (Npts)</option>
