<option value="1">Alaska</option>
<option value="2">Hawaii</option>
<option value="3">Puerto Rico</option>
<option value="4">U.S. Virgin Islands</option>
<option value="5">U.S. Pacific Trust Territories and Possessions</option>
<option value="11">Connecticut</option>
<option value="12">Maine</option>
<option value="13">Massachusetts</option>
<option value="14">New Hampshire</option>
<option value="15">Rhode Island</option>
<option value="16">Vermont</option>
<option value="21">New Jersey</option>
<option value="22">New York</option>
<option value="23">Pennsylvania</option>
<option value="31">Delaware</option>
<option value="32">District of Columbia</option>
<option value="33">Florida</option>
<option value="34">Georgia</option>
<option value="35">Maryland</option>
<option value="36">North Carolina</option>
<option value="37">South Carolina</option>
<option value="38">Virginia</option>
<option value="39">West Virginia</option>
<option value="41">Illinois</option>
<option value="42">Indiana</option>
<option value="43">Michigan</option>
<option value="44">Ohio</option>
<option value="45">Wisconsin</option>
<option value="51">Alabama</option>
<option value="52">Kentucky</option>
<option value="53">Mississippi</option>
<option value="54">Tennessee</option>
<option value="61">Iowa</option>
<option value="62">Kansas</option>
<option value="63">Minnesota</option>
<option value="64">Missouri</option>
<option value="65">Nebraska</option>
<option value="66">North Dakota</option>
<option value="67">South Dakota</option>
<option value="71">Arkansas</option>
<option value="72">Louisiana</option>
<option value="73">Oklahoma</option>
<option value="74">Texas</option>
<option value="81">Arizona</option>
<option value="82">Colorado</option>
<option value="83">Idaho</option>
<option value="84">Montana</option>
<option value="85">Nevada</option>
<option value="86">New Mexico</option>
<option value="87">Utah</option>
<option value="88">Wyoming</option>
<option value="91">California</option>
<option value="92">Oregon</option>
<option value="93">Washington</option>
<option value="106">Belize</option>
<option value="110">Costa Rica</option>
<option value="118">El Salvador</option>
<option value="127">Guatemala</option>
<option value="131">Honduras</option>
<option value="148">Mexico</option>
<option value="153">Nicaragua</option>
<option value="160">Panama Canal Zone</option>
<option value="162">Panama</option>
<option value="174">San Andres Island</option>
<option value="202">Anguilla</option>
<option value="204">Bahamas</option>
<option value="205">Barbados</option>
<option value="206">Antigua and Barbuda</option>
<option value="207">Bermuda</option>
<option value="209">Carriacou</option>
<option value="219">Cuba</option>
<option value="221">Dominica</option>
<option value="224">Dominican Republic</option>
<option value="233">Cayman Islands</option>
<option value="234">Grand Turk</option>
<option value="235">Guadeloupe</option>
<option value="236">Saint Martin</option>
<option value="237">Saint Barthelemy</option>
<option value="238">Haiti</option>
<option value="243">Jamaica</option>
<option value="252">Martinique</option>
<option value="256">Montserrat</option>
<option value="257">Mustique</option>
<option value="259">Netherlands Antilles</option>
<option value="260">Bonaire, Sint Eustatius, and Saba</option>
<option value="261">St. Kitts and Nevis - UK</option>
<option value="262">Curacao</option>
<option value="264">Sint Maarten</option>
<option value="267">Providenciales</option>
<option value="268">Puerto Rico</option>
<option value="273">Grenada and South Grenadines</option>
<option value="274">Antigua and Barbuda - UK</option>
<option value="275">St. Kitts and Nevis</option>
<option value="276">St. Lucia</option>
<option value="277">Aruba</option>
<option value="279">St. Vincent and North Grenadines</option>
<option value="280">Trinidad and Tobago</option>
<option value="281">Turks and Caicos Islands</option>
<option value="282">British Virgin Islands</option>
<option value="283">U.S. Virgin Islands</option>
<option value="303">Argentina</option>
<option value="312">Bolivia</option>
<option value="316">Brazil</option>
<option value="324">Chile</option>
<option value="327">Colombia</option>
<option value="337">Ecuador</option>
<option value="340">Falkland Islands</option>
<option value="344">French Guiana</option>
<option value="350">Guyana</option>
<option value="365">Paraguay</option>
<option value="368">Peru</option>
<option value="379">Suriname</option>
<option value="385">Uruguay</option>
<option value="388">Venezuela</option>
<option value="401">Albania</option>
<option value="402">Andorra</option>
<option value="403">Austria</option>
<option value="405">Armenia</option>
<option value="407">Azerbaijan</option>
<option value="409">Belgium</option>
<option value="410">Bosnia and Herzegovina</option>
<option value="411">Bulgaria</option>
<option value="413">Belarus</option>
<option value="415">Croatia</option>
<option value="417">Czechoslovakia</option>
<option value="418">Czech Republic</option>
<option value="419">Denmark</option>
<option value="422">Estonia</option>
<option value="425">Finland</option>
<option value="427">France</option>
<option value="428">East Germany</option>
<option value="429">Germany</option>
<option value="430">Berlin</option>
<option value="431">Gibraltar</option>
<option value="432">Georgia</option>
<option value="433">Greece</option>
<option value="437">Hungary</option>
<option value="439">Iceland</option>
<option value="441">Ireland</option>
<option value="450">Italy</option>
<option value="451">Latvia</option>
<option value="452">Lithuania</option>
<option value="453">Liechtenstein</option>
<option value="454">Luxembourg</option>
<option value="455">Macedonia</option>
<option value="456">Malta</option>
<option value="457">Moldova</option>
<option value="458">Monaco</option>
<option value="459">Montenegro</option>
<option value="461">Netherlands</option>
<option value="465">Norway</option>
<option value="467">Poland</option>
<option value="469">Portugal</option>
<option value="473">Romania</option>
<option value="475">Russia (European Part)</option>
<option value="477">Serbia and Montenegro</option>
<option value="479">San Marino</option>
<option value="480">Serbia</option>
<option value="481">Slovenia</option>
<option value="482">Spain</option>
<option value="483">Slovakia</option>
<option value="484">Sweden</option>
<option value="486">Switzerland</option>
<option value="488">Ukraine</option>
<option value="489">U.S.S.R. (European Part)</option>
<option value="493">United Kingdom</option>
<option value="494">Kosovo</option>
<option value="497">Yugoslavia</option>
<option value="500">Algeria</option>
<option value="501">South Sudan</option>
<option value="502">Angola</option>
<option value="503">Burundi</option>
<option value="504">Cameroon</option>
<option value="506">Canary Island</option>
<option value="507">Cape Verde Islands</option>
<option value="509">Central African Republic</option>
<option value="510">Botswana</option>
<option value="511">Chad</option>
<option value="513">Comoros</option>
<option value="515">Republic of the Congo</option>
<option value="517">Democratic Republic of the Congo</option>
<option value="519">Benin</option>
<option value="521">Equatorial Guinea</option>
<option value="522">Ethiopia</option>
<option value="523">Eritrea</option>
<option value="525">Djibouti</option>
<option value="526">Gabon</option>
<option value="527">The Gambia</option>
<option value="529">Ghana</option>
<option value="531">Guinea</option>
<option value="533">Cote d'Ivoire</option>
<option value="535">Kenya</option>
<option value="536">Lesotho</option>
<option value="537">Liberia</option>
<option value="538">Libya</option>
<option value="540">Madeira Islands</option>
<option value="541">Madagascar</option>
<option value="542">Malawi</option>
<option value="543">Mali</option>
<option value="545">Mauritania</option>
<option value="546">Mauritius</option>
<option value="547">Mayotte</option>
<option value="548">Morocco</option>
<option value="550">Mozambique</option>
<option value="554">Niger</option>
<option value="555">Nigeria</option>
<option value="559">Guinea-Bissau</option>
<option value="562">South Africa</option>
<option value="563">Reunion Island</option>
<option value="565">Zimbabwe</option>
<option value="566">Rwanda</option>
<option value="567">Sao Tome and Principe</option>
<option value="568">Rodrigues Islands</option>
<option value="569">Senegal</option>
<option value="570">Seychelles Islands</option>
<option value="571">Sierra Leone</option>
<option value="573">Somalia</option>
<option value="575">Namibia</option>
<option value="580">Saint Helena, Ascension, and Tristan da Cunha</option>
<option value="582">Swaziland</option>
<option value="583">Sudan</option>
<option value="585">Tanzania</option>
<option value="586">Togo</option>
<option value="588">Tunisia</option>
<option value="590">Uganda</option>
<option value="591">Egypt</option>
<option value="593">Burkina Faso</option>
<option value="597">Zambia</option>
<option value="599">Rhodesia</option>
<option value="605">Bahrain</option>
<option value="611">Cyprus</option>
<option value="632">Iran</option>
<option value="634">Iraq</option>
<option value="636">Israel</option>
<option value="639">Jordan</option>
<option value="644">Kuwait</option>
<option value="647">Lebanon</option>
<option value="658">Oman</option>
<option value="664">Qatar</option>
<option value="667">People's Democratic Republic of Yemen</option>
<option value="670">Saudi Arabia</option>
<option value="676">Syria</option>
<option value="678">United Arab Emirates</option>
<option value="679">Turkey</option>
<option value="694">Yemen</option>
<option value="701">Afghanistan</option>
<option value="702">Bhutan</option>
<option value="703">Bangladesh</option>
<option value="704">Brunei</option>
<option value="705">Bonin Islands</option>
<option value="706">Myanmar</option>
<option value="707">British Indian Ocean Territory</option>
<option value="709">Cambodia</option>
<option value="711">Sri Lanka</option>
<option value="713">China</option>
<option value="729">Hong Kong</option>
<option value="733">India</option>
<option value="736">Japan</option>
<option value="738">Kazakhstan</option>
<option value="743">Kyrgyzstan</option>
<option value="744">Laos</option>
<option value="747">Macau</option>
<option value="749">Malaysia</option>
<option value="750">Maldives</option>
<option value="751">Mongolia</option>
<option value="755">Nepal</option>
<option value="757">North Korea</option>
<option value="759">North Vietnam</option>
<option value="761">Okinawa/Ryukyu Islands</option>
<option value="764">Pakistan</option>
<option value="766">Philippines</option>
<option value="770">Russia (Asian Part)</option>
<option value="776">Singapore</option>
<option value="778">South Korea</option>
<option value="780">South Vietnam</option>
<option value="781">Taiwan</option>
<option value="782">Thailand</option>
<option value="783">Tajikistan</option>
<option value="785">Turkmenistan</option>
<option value="786">U.S.S.R. (Asian Part)</option>
<option value="788">Uzbekistan</option>
<option value="791">Vietnam</option>
<option value="800">American Samoa</option>
<option value="801">Antarctica</option>
<option value="802">Australia</option>
<option value="803">Christmas Island</option>
<option value="804">Papua New Guinea</option>
<option value="809">Palau Islands</option>
<option value="810">Federated States of Micronesia</option>
<option value="812">Cocos (Keeling) Islands</option>
<option value="813">Cook Islands</option>
<option value="817">Tuvalu</option>
<option value="821">Fiji Islands</option>
<option value="823">French Polynesia</option>
<option value="824">Kiribati</option>
<option value="826">Guam</option>
<option value="832">Indonesia</option>
<option value="834">Johnston Island</option>
<option value="840">Loyalty Islands</option>
<option value="841">Northern Mariana Islands</option>
<option value="842">Midway Islands</option>
<option value="843">Marshall Islands</option>
<option value="844">Marshall Islands</option>
<option value="845">Nauru</option>
<option value="846">New Caledonia</option>
<option value="849">New Hebrides</option>
<option value="851">New Zealand</option>
<option value="852">Niue</option>
<option value="853">Norfolk Island</option>
<option value="854">Palau</option>
<option value="861">East Timor</option>
<option value="862">Timor-Leste</option>
<option value="874">Solomon Islands</option>
<option value="881">Tonga</option>
<option value="885">Vanuatu</option>
<option value="888">Wake Island</option>
<option value="890">Wallis and Futuna Islands</option>
<option value="892">Samoa</option>
<option value="906">British Columbia</option>
<option value="911">Yukon Territory</option>
<option value="916">Alberta</option>
<option value="921">Saskatchewan</option>
<option value="926">Manitoba</option>
<option value="931">Northwest Territories</option>
<option value="934">Nunavut Territory</option>
<option value="936">Ontario</option>
<option value="941">Quebec</option>
<option value="946">New Brunswick</option>
<option value="951">Nova Scotia</option>
<option value="956">Prince Edward Island</option>
<option value="961">Newfoundland and Labrador</option>
<option value="975">Greenland</option>
<option value="977">Saint Pierre and Miquelon</option>
